#!/usr/bin/env bash
# shellcheck disable=SC1090,SC2034
# derived from "template_table"

##########################
###   DATA FUNCTIONS   ###
##########################

get_data()
{
    local -n gd_return="$1"
    gd_return=()

    local -a re_parts=(
        ^declare[[:space:]]+  # discard ubiquitous 'declare'
        \([^[:space:]]+\)     # capture 1, attributes
        [[:space:]]
        \([^=]+\)             # capture 2, variable name
        \(                    # capture 3 conditional
            "="
            \(.*\)            # capture 4, value
        \)?
    )
    IFS="" printf -v regex "%s" "${re_parts[@]}"

    while read -r; do
        if [[ "$REPLY" =~ $regex ]]; then
            local name="${BASH_REMATCH[2]}"
            local attr="${BASH_REMATCH[1]}"
            local value="${BASH_REMATCH[4]}"
            if [[ "$value" =~ ^\"(.*)\"$ ]]; then
                value="${BASH_REMATCH[1]}"
            fi
            gd_return+=( "$name$DELIM$attr$DELIM$value" )
        fi
    done < <( declare -p )
}

get_column_sizes()
{
    local -n gcs_sizes="$1"
    local -n gcs_source="$2"

    local IFS="$DELIM"
    local -a gcs_row

    # Make array of 0 max sizes from split of first row:
    read -ra gcs_row <<< "${gcs_source[0]}"
    gcs_sizes=()
    for el in "${gcs_row[@]}"; do
        gcs_sizes+=( 0 )
    done

    local -i index rowlen elmax curlen

    for row in "${gcs_source[@]}"; do
        read -ra gcs_row <<< "$row"

        (( index = 0 ))
        for el in "${gcs_row[@]}"; do
            local curlen="${#el}"
            if (( curlen > gcs_sizes[index] )); then
                (( gcs_sizes[index] = curlen ))
            fi
            (( ++index ))
        done
    done
}

get_print_line_format()
{
    local gplf_return_name="$1"
    local -n gplf_return="$1"
    local -n gplf_columns="$2"
    local gplf_gutter="${3:-  }"

    # Using '%-x.xs' to force an exact width, padding
    # or truncating as necessary.

    # double-up sizes to be consumed two-at-a-time by %%-%d.%ds
    local -a gplf_dup
    for size in "${gplf_columns[@]}"; do
        gplf_dup+=( "$size" "$size" )
    done

    printf -v "$gplf_return_name" "%%-%d.%ds${gplf_gutter}" "${gplf_dup[@]}"
    gplf_return="${gplf_return:0: -${#gplf_gutter}}"
}

predict_rendered_line_size()
{
    local -n prls_return="$1"
    local -n prls_columns="$2"
    local prls_gutter="${3:-  }"

    prls_return=$(( ${#prls_gutter} * ( ${#prls_columns[*]} - 1 ) ))

    for size in "${prls_columns[@]}"; do
        (( prls_return += size ))
    done
}

#####################
###   FILTERING   ###
#####################

get_filtered_data()
{
    local -n gfd_target="$1"
    local -n gfd_data="$2"
    local gfd_filter_test="test_$3"

    for el in "${gfd_data[@]}"; do
        if "$gfd_filter_test" "$el"; then
            gfd_target+=( "$el" )
        fi
    done
}

# Test functions to match filter options:
test_array()
{
    IFS="$DELIM" read -ra ta_row <<< "$1"
    [[ "${ta_row[1]}" =~ a ]]
}

test_export()
{
    IFS="$DELIM" read -ra ta_row <<< "$1"
    [[ "${ta_row[1]}" =~ x ]]
}

test_hash()
{
    IFS="$DELIM" read -ra ta_row <<< "$1"
    [[ "${ta_row[1]}" =~ A ]]
}

test_integer()
{
    IFS="$DELIM" read -ra ta_row <<< "$1"
    [[ "${ta_row[1]}" =~ i ]]
}

test_read-only()
{
    IFS="$DELIM" read -ra ta_row <<< "$1"
    [[ "${ta_row[1]}" =~ r ]]
}

##################################
###   PWB CALLBACK FUNCTIONS   ###
##################################

print_line()
{
    local -n pl_dsource="$2"
    IFS="$DELIM" read -ra pl_row <<< "${pl_dsource[$1]}"
    # shellcheck disable=SC2059
    printf -v tline "$PRINT_LINE_FORMAT" "${pl_row[@]}"
    printf "%-*.*s" "$3" "$3" "$tline"
}

print_top()
{
    # create array for printing
    local -a pt_lines=(
        "$BASIC_TOP_NAME"
        ""
    )
    printf -v pt_lines[1] $'Filter: \e[32;1m%s\e[39;22m' "$SA_FILTER"

    printf $'\e[48;5;235m'
    pwb_print_array pt_lines "${TOP_MARG_ARGS[@]}"
    printf $'\e[49m'
}

print_bottom()
{
    local -i total index="$1"
    local handle_name="$5"
    local -a pb_lines

    pwb get_data_count "$handle_name" -v total
    printf -v pb_lines[0] \
           $'item \e[32;1m%d\e[39;22m of \e[32;1m%d\e[39;22m.' \
           $(( index+1 )) "$total"
    printf $'\e[48;5;235m'
    pwb_print_array pb_lines "${BOTTOM_MARG_ARGS[@]}"
    printf $'\e[49m'
}

print_left()
{
    # will be either print_left_empty or print_left_scrollbar
    "$print_left_func" "$@"
}

# No-scrollbar left margin printer
print_left_empty()
{
    local -a ple_lines=()
    pwb_print_array ple_lines "${LEFT_MARG_ARGS[@]}"
}

# Scrollbar left margin printer
print_left_scrollbar()
{
    local handle_name="$5"
    pwb get_dimensions "$handle_name"

    local -i width="${PWB_ASSOC[margin_left]}"
    local -i left=$(( width - 2 ))

    local -a pls_chars

    local -a SB_ARGS=(
        -t "${PWB_ASSOC[row_top]}"
        -s "${PWB_ASSOC[data_rows]}"
        -v "${PWB_ASSOC[pager_lines]}"
        -c "${PWB_ASSOC[pager_lines]}"
    )

    pwb_get_scroll_bar pls_chars "${SB_ARGS[@]}"

    for char in "${pls_chars[@]}"; do
        printf $'\e[%dX\e[%dG%s\e[1E' "$width" "$left" "$char"
    done
}


########################
###   EXEC SECTION   ###
########################

execution_manager()
{
    local keyp="$1"
    local em_psource="$4"

    local -i ecode=0
    local em_func
    if pwb_keybinder func KEYFUNCS -v em_func -k "$keyp"; then
        "$em_func" "$@"
        ecode="$?"
        printf $'\e[H\e[2J'
        pwb print_all "$em_psource"
    fi

    return "$ecode"
}

exec_help()
{
    local eh_keyp
    pwb_keybinder help KEYBINDINGS -v eh_keyp

    # Recursively call execution_manager with exit key from kebinder
    # in case it's one that should initiate another action
    shift
    execution_manager "$eh_keyp" "$@"
    local -i ecode="$?"
    if [[ "$eh_keyp" == 'q' ]]; then
        ecode=1
    fi

    return "$ecode"
}

exec_inspect()
{
    local -n ex_dsource="$3"
    IFS="$DELIM" read -ra ex_row <<< "${ex_dsource[$2]}"
    local varname="${ex_row[0]}"

    local -a ex_lines
    printf -v ex_lines[${#ex_lines[*]}] \
           $'\e[48;5;238m    Variable \e[32;1m%s    \e[49;39;22m' "$varname"

    if pwb audit_var -ac "$varname"; then
        read -ra ei_row <<< "$PWB_VALUE"
        printf -v ex_lines[${#ex_lines[*]}] \
               $'      type: \e[32;1m%s\e[39;22m' "${ei_row[0]}"
        printf -v ex_lines[${#ex_lines[*]}] \
               $'   context: \e[32;1m%s\e[39;22m' "${ei_row[1]}"
        printf -v ex_lines[${#ex_lines[*]}] \
               $'attributes: \e[32;1m%s\e[39;22m' "${ei_row[2]}"
    else
        ex_lines+=( "$PWB_ERROR" )
    fi

    pwb_conduct_dialog ex_lines
}

exec_filter()
{
    local ef_handle="$4"

    local -a options=(
        none
        array
        export
        hash
        integer
        read-only
    )

    # Convert selected filter to start_selections argument string:
    local -a flags_arr
    for opt in "${options[@]}"; do
        if [[ "$opt" == "$SA_FILTER" ]]; then
            flags_arr+=( 1 )
        else
            flags_arr+=( 0 )
        fi
    done
    local flags
    printf -v flags "%d" "${flags_arr[@]}"

    local -a hlines=(
        "Select one of the following filters."
        ""
    )

    local keyp

    local -a selargs=(
        options
        "$ef_handle"
        -h hlines
        -jc
        -kkeyp
        -tnumbers
        -sflags
    )

    if pwb_selector "${selargs[@]}"; then
        SA_FILTER="${options[$SELECTED]}"
        return 1
    fi

    return 0
}


###########################
###   SETUP FUNCTIONS   ###
###########################

# Set top margin for info, side margins for centering
set_margins()
{
   local sm_handle="$1"
   local -i sm_content_size="$2"

   pwb get_dimensions
   local -i columns="${PWB_ASSOC[screen_cols]}"

   # Adjust if content size it would overflow:
   if (( sm_content_size > columns - 2 )); then
       (( sm_content_size = columns - 2 ))
   fi

   # Always leave 2 spaces for left scrollbar:
   local -i to_distribute=$(( columns - sm_content_size - 2 ))
   local -i left=2 right=0

   # Only center if more than 2 spare spaces
   if (( columns > to_distribute )); then
       (( right = to_distribute / 2 ))
       (( left += to_distribute - right ))
   fi

   pwb set_margins "$sm_handle" 4 "$right" 1 "$left"
}

content_needs_scrollbar()
{
    local cns_handle="$1"
    pwb get_dimensions "$cns_handle"
    (( PWB_ASSOC[data_rows] > 0 && PWB_ASSOC[data_rows] > PWB_ASSOC[pager_lines] ))
}

# Trap signal to handle abrupt exits
exit_trap() { printf $'\e[39;49;22m\e[H\e[2J'; pwb restore; }

is_app_exit_key()
{
    local keyp="$1"
    [[ "$keyp" =~ ('q'|$'\e') ]]
}

start_instance()
{
    local si_keyp_name="$1"
    local si_data_name="$2"

    local -n SI_DATA="$si_data_name"

    # Measure data for formatting
    local -a COLUMN_SIZES
    get_column_sizes COLUMN_SIZES "$si_data_name"

    local PRINT_LINE_FORMAT
    get_print_line_format PRINT_LINE_FORMAT COLUMN_SIZES
    local -i CONTENT_WIDTH
    predict_rendered_line_size CONTENT_WIDTH COLUMN_SIZES

    # Declare Handle
    declare -a DECLARE_ARGS=(
        SI_DATA
        "${#SI_DATA[*]}"
        print_line
        -t print_top
        -b print_bottom
        -l print_left
        -e execution_manager
    )
    declare SI_HANDLE
    pwb declare SI_HANDLE "${DECLARE_ARGS[@]}"

    # Divide the screen using margins
    set_margins SI_HANDLE "$CONTENT_WIDTH"
    # Set global margin-printing argument arrays
    declare -a TOP_MARG_ARGS BOTTOM_MARG_ARGS LEFT_MARG_ARGS
    pwb_get_margin_args SI_HANDLE TOP_MARG_ARGS "" BOTTOM_MARG_ARGS LEFT_MARG_ARGS
    # Set to use or not use a left-margin scrollbar
    declare print_left_func=print_left_empty
    if content_needs_scrollbar SI_HANDLE; then
        print_left_func=print_left_scrollbar
    fi

    pwb start SI_HANDLE -a KEYMAP -k "$si_keyp_name"
}

start_application()
{
    # Prepare data source
    local -a SA_DATA
    get_data SA_DATA

    local -a SA_FILTERED_DATA

    local SA_FILTER="none"
    local cur_data_name="bogus"

    local sa_keyp

    while ! is_app_exit_key "$sa_keyp"; do
        if [[ "$SA_FILTER" == "none" ]]; then
            cur_data_name="SA_DATA"
        else
            SA_FILTERED_DATA=()
            get_filtered_data SA_FILTERED_DATA SA_DATA "$SA_FILTER"
            cur_data_name=SA_FILTERED_DATA
        fi

        printf $'\e[2J'
        start_instance sa_keyp "$cur_data_name"
    done
}


###########################
###   BEGIN EXECUTION   ###
###########################

enable pwb

declare DELIM="|"

# Using source scripts
declare -a SOURCE_ARGS=(
    pwb_exit_on_error
    pwb_get_margin_args
    pwb_print_array
    pwb_get_scroll_bar
    pwb_conduct_dialog
    pwb_keybinder
    pwb_selector
)
source <( pwb_sources "${SOURCE_ARGS[@]}" )

### KEYBINDING ###
declare -a KEYBINDINGS=(
    "h" exec_help    "Show help"
    "f" exec_filter  "Filter contents"
    "i" exec_inspect "Inspect file"
)
declare KEYMAP
declare -a KEYFUNCS
pwb_keybinder prep KEYBINDINGS -v KEYMAP -f KEYFUNCS

# For print_top contents
declare BASIC_TOP_NAME="PWB FILTER TEMPLATE"

# Use trap/signal to handle possible abrupt exits
trap exit_trap EXIT SIGINT SIGABRT
pwb init

start_application

## BEGIN_DOC
## Showing the collection of Bash shell
## variables for a diverse dataset suitable
## for filtering.
##
## The code is optimized for use as a template,
## grouping and segregating code into functions
## with the goal of making it easier to modify
## derived scripts.
## END_DOC
