#!/usr/bin/env bash

##########################
###   DATA FUNCTIONS   ###
##########################

get_data()
{
   local -n gd_return="$1"
   gd_return=()

   shopt -s nullglob
   local -a gd_files=( * )
   shopt -u nullglob

   # Get name / filetype / size from stat:
   local format="%n${DELIM}%F${DELIM}%s"

   while read -r; do
       gd_return+=( "$REPLY" )
   done < <( stat -c "$format" "${gd_files[@]}" )
}

get_column_sizes()
{
    local -n gcs_sizes="$1"
    local -n gcs_source="$2"

    local IFS="$DELIM"
    local -a gcs_row

    # Make array of 0 max sizes from split of first row:
    read -ra gcs_row <<< "${gcs_source[0]}"
    gcs_sizes=()
    for el in "${gcs_row[@]}"; do
        gcs_sizes+=( 0 )
    done

    local -i index rowlen elmax curlen

    for row in "${gcs_source[@]}"; do
        read -ra gcs_row <<< "$row"

        (( index = 0 ))
        for el in "${gcs_row[@]}"; do
            local curlen="${#el}"
            if (( curlen > gcs_sizes[index] )); then
                (( gcs_sizes[index] = curlen ))
            fi
            (( ++index ))
        done
    done
}

get_content_size()
{
    local -n gfs_return="$1"
    local -n gfs_columns="$2"

    gfs_return=$(( gfs_gutter_size * ( ${#gfs_columns[*]} - 1 ) ))

    for size in "${gfs_columns[@]}"; do
        (( gfs_return += size ))
    done
}


##################################
###   PWB CALLBACK FUNCTIONS   ###
##################################

print_line()
{
    local -n pl_dsource="$2"
    IFS="$DELIM" read -ra pl_row <<< "${pl_dsource[$1]}"
    printf -v tline "$PRINT_LINE_FORMAT" "${pl_row[@]}"
    printf "%-*.*s" "$3" "$3" "$tline"
}

print_top()
{
    # Generate progress info string
    local -i total index="$1"
    local handle_name="$5"
    pwb get_data_count "$handle_name" -v total
    printf -v progress_line \
           $'Item \e[32;1m%d\e[39;22m of \e[32;1m%d\e[39;22m.' \
           $(( index+1 )) "$total"

    # Create array for printing
    local -a pt_lines=(
        "$BASIC_TOP_NAME"
        "$BASIC_TOP_PROMPT"
        ""
        "$progress_line"
    )

    printf $'\e[48;5;235m'
    pwb_print_array pt_lines "${TOP_MARG_ARGS[@]}"
    printf $'\e[49m'
}


print_left()
{
    # will be either print_left_empty or print_left_scrollbar
    "$print_left_func" "$@"
}

# No-scrollbar left margin printer
print_left_empty()
{
    local -a ple_lines=()
    pwb_print_array ple_lines "${LEFT_MARG_ARGS[@]}"
}

# Scrollbar left margin printer
print_left_scrollbar()
{
    local handle_name="$5"
    pwb get_dimensions "$handle_name"

    local -i width="${PWB_ASSOC[margin_left]}"
    local -i left=$(( width - 2 ))

    local -a pls_chars

    local -a SB_ARGS=(
        -t "${PWB_ASSOC[row_top]}"
        -s "${PWB_ASSOC[data_rows]}"
        -v "${PWB_ASSOC[pager_lines]}"
        -c "${PWB_ASSOC[pager_lines]}"
    )

    pwb_get_scroll_bar pls_chars "${SB_ARGS[@]}"

    for char in "${pls_chars[@]}"; do
        printf $'\e[%dX\e[%dG%s\e[1E' "$width" "$left" "$char"
    done
}


########################
###   EXEC SECTION   ###
########################

execute_line()
{
    local keyp="$1"
    local el_psource="$4"

    local -i ecode=0
    local el_func
    if pwb_keybinder func KEYFUNCS -v el_func -k "$keyp"; then
        "$el_func" "$@"
        ecode="$?"
        printf $'\e[H\e[2J'
        pwb print_all "$el_psource"
    fi

    return "$ecode"
}

exec_help()
{
    local eh_keyp
    pwb_keybinder help KEYBINDINGS -v eh_keyp

    # Recursively call execute_line with exit key from kebinder
    # in case it's one that should initiate another action
    execute_line "$eh_keyp" "${@:1}"
    local -i ecode="$?"
    if [[ "$eh_keyp" == 'q' ]]; then
        ecode=1
    fi

    return "$ecode"
}

exec_inspect()
{
    local -n ex_dsource="$3"
    IFS="$DELIM" read -ra ex_row <<< "${ex_dsource[$2]}"
    local filename="${ex_row[0]}"

    # Paired specs to align for presentation
    local -a STAT_FIELDS=(
        "name"        "%n"  # must be first element
        "file type"   "%F"  # must be second element
        "size"        "%s"
        "owner"       "%U"
        "permissions" "%A"
        "last change" "%y"
    )

    # measure labels for formatting
    local -i len_label=0
    local -i cur_len

    # compile tokens list to build format string
    local -a tokens=()

    # Track index to detect field
    local -i index=0
    for el in "${STAT_FIELDS[@]}"; do
        if (( index % 2 == 0 )); then
            cur_len="${#el}"
            if (( cur_len > len_label )); then
                len_label="$cur_len"
            fi
        else
            tokens+=( "$el" )
        fi
        (( ++index ))
    done

    # Get label-correlating array of attributes
    local DELIM="|"
    printf -v format "%s${DELIM}" "${tokens[@]}"
    format="${format:0: -1}"
    IFS="$DELIM" read -ra attributes <<< $( stat -c "$format" "$filename" )

    local -a ex_lines

    index=0
    for el in "${STAT_FIELDS[@]}"; do
        if (( index % 2 == 0 )); then
            printf -v ex_lines[${#ex_lines[*]}] \
                   $'%*s: \e[32;1m%s\e[39;22m'  \
                   "$len_label" \
                   "$el"        \
                   "${attributes[$(( index / 2 ))]}"
        fi
        (( ++index ))
    done

    pwb_conduct_dialog ex_lines
}


###########################
###   SETUP FUNCTIONS   ###
###########################

# Set top margin for info, side margins for centering
set_margins()
{
   local sm_handle="$1"
   local -i sm_content_size="$2"

   pwb get_dimensions
   local -i left right
   local -i columns="${PWB_ASSOC[screen_cols]}"

   # Only center if more than 2 spare spaces
   if (( columns > sm_content_size+2 )); then
       (( columns -= 2 ))
       (( right = (columns - sm_content_size) / 2 ))
       (( left = columns - sm_content_size - right ))
   else
       (( left = 2, right = 0 ))
   fi

   pwb set_margins "$sm_handle" 4 "$right" 1 "$left"
}

content_needs_scrollbar()
{
    local cns_handle="$1"
    pwb get_dimensions "$cns_handle"
    (( PWB_ASSOC[data_rows] > 0 && PWB_ASSOC[data_rows] > PWB_ASSOC[pager_lines] ))
}

# Trap signal to handle abrupt exits
exit_trap() { printf $'\e[39;49;22m\e[H\e[2J'; pwb restore; }


###########################
###   BEGIN EXECUTION   ###
###########################

enable pwb

declare DELIM="|"

# Using source scripts
declare -a SOURCE_ARGS=(
    pwb_exit_on_error
    pwb_get_margin_args
    pwb_print_array
    pwb_get_scroll_bar
    pwb_conduct_dialog
    pwb_keybinder
)
source <( pwb_sources "${SOURCE_ARGS[@]}" )

### KEYBINDING ###
declare -a KEYBINDINGS=(
    "?"      exec_help    "Show help"
    "key_f1" exec_help    "Show help"
    "i"      exec_inspect "Inspect file"
)
declare KEYMAP
declare -a KEYFUNCS
pwb_keybinder prep KEYBINDINGS -v KEYMAP -f KEYFUNCS

# Prepare data source
declare -a PDATA
get_data PDATA

# Measure data for formatting
declare -a COLUMN_SIZES
get_column_sizes COLUMN_SIZES PDATA
declare PRINT_LINE_FORMAT
printf -v PRINT_LINE_FORMAT "%%-%ds  " "${COLUMN_SIZES[@]}"
PRINT_LINE_FORMAT="${PRINT_LINE_FORMAT:0: -2}"
declare -i CONTENT_WIDTH
get_content_size CONTENT_WIDTH COLUMN_SIZES

# Declare Handle
declare -a DECLARE_ARGS=(
    PDATA
    "${#PDATA[*]}"
    print_line
    -t print_top
    -l print_left
    -e execute_line
)
declare PHANDLE
pwb declare PHANDLE "${DECLARE_ARGS[@]}"

# Divide the screen using margins
set_margins PHANDLE "$CONTENT_WIDTH"
# Set global margin-printing argument arrays
declare -a TOP_MARG_ARGS
pwb_get_margin_args PHANDLE TOP_MARG_ARGS
# Set to use or not use a left-margin scrollbar
declare print_left_func=print_left_empty
if content_needs_scrollbar PHANDLE; then
    print_left_func=print_left_scrollbar
fi

# Use trap/signal to handle possible abrupt exits
trap exit_trap EXIT SIGINT SIGABRT

# For print_top contents
declare BASIC_TOP_NAME="PWB ACTIONS TEMPLATE"
declare BASIC_TOP_PROMPT=$'Press "\e[32;1m?\e[39;22m"'`
        `$' or "\e[32;1mf1\e[39;22m" for help,'`
        `$' or "\e[32;1mq\e[39;22m" to quit.'

pwb init
pwb start PHANDLE -a KEYMAP

## BEGIN_DOC
## This script introduces good behavior features.
## Second in a progression of template scripts.
##
## 1. Margins are used to divide the screen
##    into sections.  Top margin for info,
##    side margins for centering content, left
##    margin for scrollbar, if needed.
## 2. Using trap/signal to restore the terminal
##    in case of early exit due to an error.
## 3. Introduce pwb_sources, a library of
##    utilities for doing common useful things.
## END_DOC
