#!/usr/bin/env bash

##########################
###   DATA FUNCTIONS   ###
##########################

get_data()
{
   local -n gd_return="$1"

   # Get list of files to 'stat' for additional information
   local -a gd_files
   shopt -s nullglob
   gd_files=( * )
   shopt -u nullglob

   # Get table for cross-referencing file types to color,
   # according to user's LS_COLORS values or by using
   # 'dircolors' to get the default LS_COLORS value:
   declare -A color_table=()
   create_type_color_reference color_table

   local IFS="$DELIM"
   local colstr

   while read -r; do
       read -ra gd_row <<< "$REPLY"
       colstr="${color_table[${gd_row[1]}]}"
       if [ -z "$colstr" ]; then
           colstr="0"
       fi

       # Use execute color if no other color in use:
       if [ -x "${gd_row[0]}" ] && [[ "$colstr" == "0" ]]; then
           gd_row[1]="executable"
           REPLY="${gd_row[*]}"
           colstr="${color_table[executable]}"
       fi

       # Setting to '0' will cancel highlighting, change value
       # the 39 for using the default foreground color:
       if [[ "$colstr" == "0" ]]; then
           colstr="39"
       fi

       gd_return+=( "$REPLY${DELIM}$colstr" )
   done < <( stat -c "%n${DELIM}%F" "${gd_files[@]}" )
}


################################
### PWB CALLBACK FUNCTIONS   ###
################################

print_line()
{
    local -n pl_dsource="$2"
    IFS="$DELIM" read -ra pl_row <<< "${pl_dsource[$1]}"

    # Size the text before applying the colors
    printf -v tline "%-*.*s" "$3" "$3" "${pl_row[0]}"
    printf $'\e[%sm%s\e[39;22m' "${pl_row[2]}" "$tline"
}

print_top()
{
    local -n pl_dsource="$2"
    IFS="$DELIM" read -ra pt_row <<< "${pl_dsource[$1]}"

    local -i char_count="$3"
    local -a pt_lines=(
        "PWB ARRAYS TEMPLATE"
        "${pt_row[0]}"
        "${pt_row[1]}"
        $'Press "\e[32;1mq\e[39;22m" to exit.'
    )
    local -a print_array_args=(
        -t 1
        -l 1
        -w "$char_count"
        -c "$TOP_MARGIN"
        -j c
    )

    pwb_print_array pt_lines "${print_array_args[@]}"
}

#############################
###   UTILITY FUNCTIONS   ###
#############################

exit_trap() { printf $'\e[39;49;22m\e[H\e[2J'; pwb restore; }

create_type_color_reference()
{
    local array_name="$1"
    local -n ctcr_array="$array_name"

    # Use default colors if LS_COLORS not yet set:
    if [ -z "$LS_COLORS" ]; then
        exec $( dircolors )
    fi

    local -a colors
    if [ -n "$LS_COLORS" ]; then
        IFS=':' read -ra colors <<< "$LS_COLORS"
    fi

    for color in "${colors[@]}"; do
        IFS='=' read -ra color_spec <<< "$color"

        local type_name="${color_spec[0]}"
        local type_color="${color_spec[1]}"

        case "$type_name" in
            di   ) ctcr_array[directory]="$type_color" ;;
            rs   ) ctcr_array[regular]="$type_color" ;;
            ln   ) ctcr_array["symbolic link"]="$type_color" ;;
            pi   ) ctcr_array[fifo]="$type_color" ;;
            so   ) ctcr_array[socket]="$type_color" ;;
            bd   ) ctcr_array["block device special file"]="$type_color" ;;
            "cd" ) ctcr_array["char device special file"]="$type_color" ;;
            ex   ) ctcr_array["executable"]="$type_color" ;;
        esac
    done
}


############################
###   EXECUTION BEGINS   ###
############################

# Establish global DELIM character for creating and splitting arrays:
declare DELIM="|"

enable pwb

# Using source scripts
declare -a SOURCE_ARGS=(
    pwb_exit_on_error
    pwb_print_array
)
source <( pwb_sources "${SOURCE_ARGS[@]}" )

# Prepare data source
declare -a PDATA
get_data PDATA

# Declare Handle
declare -a DECLARE_ARGS=(
    PDATA
    "${#PDATA[*]}"
    print_line
    -t print_top
)
declare PHANDLE
pwb declare PHANDLE "${DECLARE_ARGS[@]}"

# Use 'constant' for consistency in set_margins and print_top:
declare -i TOP_MARGIN=5

# Divide screen by using margins:
pwb set_margins PHANDLE "$TOP_MARGIN" 0 0

# Use trap/signal to handle possible abrupt exits
trap exit_trap EXIT SIGINT SIGABRT

pwb init
pwb start PHANDLE

## BEGIN_DOC
## Enhancement of pwb_template_divided, base for
## pwb_template_xxx
##
## Associated item data should be stored together
## for efficient access.  Accommodations for array
## use are found in the 'get_data', 'print_line',
## and 'print_top' functions.
##
## As usual, refer to this sample's man page for
## a more detailed discussion of strategies and
## methods.
## END_DOC
