#!/usr/bin/env bash

##########################
###   DATA FUNCTIONS   ###
##########################

get_data()
{
   local -n gd_return="$1"

   shopt -s nullglob
   gd_return=( * )
   shopt -u nullglob
}

predict_rendered_line_size()
{
    local -n prls_return="$1"
    local -n prls_content="$2"

    prls_return=0

    for el in "${prls_content[@]}"; do
        local -i curlen="${#el}"
        if (( curlen > prls_return )); then
            (( prls_return = curlen ))
        fi
    done
}


##################################
###   PWB CALLBACK FUNCTIONS   ###
##################################

print_line()
{
    local -n pl_dsource="$2"
    printf "%-*.*s" "$3" "$3" "${pl_dsource[$1]}"
}

print_top()
{
    # create array for printing
    local -a pt_lines=(
        "$BASIC_TOP_NAME"
        "$BASIC_TOP_PROMPT"
    )

    printf $'\e[48;5;235m'
    pwb_print_array pt_lines "${TOP_MARG_ARGS[@]}"
    printf $'\e[49m'
}

print_bottom()
{
    local -i total index="$1"
    local handle_name="$5"
    local -a pb_lines

    pwb get_data_count "$handle_name" -v total
    printf -v pb_lines[0] \
           $'item \e[32;1m%d\e[39;22m of \e[32;1m%d\e[39;22m.' \
           $(( index+1 )) "$total"
    printf $'\e[48;5;235m'
    pwb_print_array pb_lines "${BOTTOM_MARG_ARGS[@]}"
    printf $'\e[49m'
}

print_left()
{
    # will be either print_left_empty or print_left_scrollbar
    "$print_left_func" "$@"
}

# No-scrollbar left margin printer
print_left_empty()
{
    local -a ple_lines=()
    pwb_print_array ple_lines "${LEFT_MARG_ARGS[@]}"
}

# Scrollbar left margin printer
print_left_scrollbar()
{
    local handle_name="$5"
    pwb get_dimensions "$handle_name"

    local -i width="${PWB_ASSOC[margin_left]}"
    local -i left=$(( width - 2 ))

    local -a pls_chars

    local -a SB_ARGS=(
        -t "${PWB_ASSOC[row_top]}"
        -s "${PWB_ASSOC[data_rows]}"
        -v "${PWB_ASSOC[pager_lines]}"
        -c "${PWB_ASSOC[pager_lines]}"
    )

    pwb_get_scroll_bar pls_chars "${SB_ARGS[@]}"

    for char in "${pls_chars[@]}"; do
        printf $'\e[%dX\e[%dG%s\e[1E' "$width" "$left" "$char"
    done
}


###########################
###   SETUP FUNCTIONS   ###
###########################

# Set top margin for info, side margins for centering
set_margins()
{
   local sm_handle="$1"
   local -i sm_content_size="$2"

   pwb get_dimensions
   local -i columns="${PWB_ASSOC[screen_cols]}"

   # Always leave 2 spaces for left scrollbar:
   local -i to_distribute=$(( columns - sm_content_size - 2 ))
   local -i left=2 right=0

   # Only center if more than 2 spare spaces
   if (( columns > to_distribute )); then
       (( right = to_distribute / 2 ))
       (( left += to_distribute - right ))
   fi

   pwb set_margins "$sm_handle" 4 "$right" 1 "$left"
}

content_needs_scrollbar()
{
    local cns_handle="$1"
    pwb get_dimensions "$cns_handle"
    (( PWB_ASSOC[data_rows] > 0 && PWB_ASSOC[data_rows] > PWB_ASSOC[pager_lines] ))
}

# Trap signal to handle abrupt exits
exit_trap() { printf $'\e[39;49;22m\e[H\e[2J'; pwb restore; }


###########################
###   BEGIN EXECUTION   ###
###########################

enable pwb

declare DELIM="|"

# Using source scripts
declare -a SOURCE_ARGS=(
    pwb_exit_on_error
    pwb_get_margin_args
    pwb_print_array
    pwb_get_scroll_bar
)
source <( pwb_sources "${SOURCE_ARGS[@]}" )

# Prepare data source
declare -a PDATA
get_data PDATA

# Measure data for formatting
declare -i CONTENT_WIDTH
predict_rendered_line_size CONTENT_WIDTH PDATA

# Declare Handle
declare -a DECLARE_ARGS=(
    PDATA
    "${#PDATA[*]}"
    print_line
    -t print_top
    -b print_bottom
    -l print_left
)
declare PHANDLE
pwb declare PHANDLE "${DECLARE_ARGS[@]}"

# Divide the screen using margins
set_margins PHANDLE "$CONTENT_WIDTH"
# Set global margin-printing argument arrays
declare -a TOP_MARG_ARGS BOTTOM_MARG_ARGS LEFT_MARG_ARGS
pwb_get_margin_args PHANDLE TOP_MARG_ARGS "" BOTTOM_MARG_ARGS LEFT_MARG_ARGS
# Set to use or not use a left-margin scrollbar
declare print_left_func=print_left_empty
if content_needs_scrollbar PHANDLE; then
    print_left_func=print_left_scrollbar
fi

# Use trap/signal to handle possible abrupt exits
trap exit_trap EXIT SIGINT SIGABRT

# For print_top contents
declare BASIC_TOP_NAME="PWB DIVIDED TEMPLATE"
declare BASIC_TOP_PROMPT=$'Press "\e[32;1mq\e[39;22m" to quit'

pwb init
pwb start PHANDLE

## BEGIN_DOC
## This script introduces good behavior features.
## Second in a progression of template scripts.
##
## 1. Margins are used to divide the screen
##    into sections.  Top margin for info,
##    side margins for centering content, left
##    margin for scrollbar, if needed.
## 2. Using trap/signal to restore the terminal
##    in case of early exit due to an error.
## 3. Introduce pwb_sources, a library of
##    utilities for doing common useful things.
## END_DOC
