.TH pwb 7 2026-01-03
.nr main_page 1
.SH NAME
.B pwb
\- pager with benefits: samples
.SH DESCRIPTION
.PP
Sometimes the best documentation is a working example.
.TP
.BR NOTE :
It can be challenging to copy man page source code to another file.
Refer to
.B "COPYING SOURCE CODE"
at the end of this document for ideas on how to do this.


.SH EXAMPLES
.PP
This section will show a minimal implementation, followed by
subsections that enhance parts to accomplish more specific
goals.

.so pwb.7.d/minimal_app.7
.so pwb.7.d/add_on_intro.7
.so pwb.7.d/key_triggers.7
.so pwb.7.d/keybinder.7
.so pwb.7.d/copying_source.7















