#!/usr/bin/env bash
declare PREFIX=#PREFIX#

# Get app prefix from first three characters of the called function,
# accommodating either 'pwb_sources' or 'ate_sources':
declare APP_PREFIX="${0##*/}"
APP_PREFIX="${APP_PREFIX:0:3}"

if [[ "$APP_PREFIX" != "pwb" ]] && [[ "$APP_PREFIX" != "ate" ]]; then
    echo "APP_PREFIX '$APP_PREFIX' breaks nameing convention necessary for success." >&2
    exit 1
fi

# declare ATE_PATH="${PREFIX}/lib/ate_sources"
declare PWB_PATH="${PREFIX}/share/pwb/sources"

declare SOURCES_PATH="$PWB_PATH"

get_scripts_inventory()
{
    local -n gs_list="$1"
    gs_list=()
    for file in ${SOURCES_PATH}/*; do
        if ! [ -d "$file" ]; then
            # remove page
            file="${file##*/}"
            # accept only prefix 'pwb_' without any extension:
            if [[ "$file" =~ pwb_[^.]+$ ]]; then
                # discard unincludable script
                if [[ "$file" != "pwb_browser" ]]; then
                    gs_list+=( "$file" )
                fi
            fi
        fi
    done
}

script_exists()   { [ -f "${SOURCE_PATH}/$1" ]; }
function_loaded() { [[ $( type -f "$1" 2>/dev/null ) == "function" ]]; }

show_usage()
{
    local sname
    printf -v sname $'\e[1m%s\e[22m' "${APP_PREFIX}_sources"
    cat <<EOF
USAGE:
   $sname [help] [source_name ...]

Display this usage message:
   $sname help

Display a browsable list of all available sources:
   $sname

Display man page for a source:
   $sname man ${APP_PREFIX}_exit_on_error

Sourcing files
   Include the following line in your Bash script:
      source <( $sname ${APP_PREFIX}_exit_on_error )

   Any number of sources can be added after $sname.
   Sources will not be loaded twice, and dependencies
   will be automatically loaded.

Sourcing all available files
   source <( $sname all )

   This will load all of the available sources in the
   script
EOF
    }

return_source_name()
{
    if ! function_loaded "$1"; then
        local prefix="${1%%_*}"
        local path="$SOURCES_PATH/$1"
        if [ -f "$path" ]; then
            echo -n "$path"
        fi
    fi
}

return_sources_script()
{
    for func in "$@"; do
        if ! function_loaded "$func"; then
            local prefix="${func%%_*}"
            local path="$SOURCES_PATH/$func"
            if [ -f "$path" ]; then
                echo "if ! declare -f $func >/dev/null; then source $path; fi"
            fi
        fi
    done
}

show_func_doc()
{
    local path="$1"
    local IFS=$'\n'
    local -a lines=( $( grep ^##\\\([[:space:]].*\\\)\\?$ "$path" ) )

    local -i progress=0
    local line cline
    for line in "${lines[@]}"; do
        [[ "$line" =~ ^##[[:space:]](.*)$ ]]
        cline="${BASH_REMATCH[1]}"
        if [ "$progress" -eq 0 ] && [[ "$cline" == "BEGIN_DOC" ]]; then
            echo
            (( ++progress ))
        elif [ "$progress" -eq 1 ]; then
            if [[ "$cline" != "END_DOC" ]]; then
                printf "%s\n" "$cline"
            else
                (( ++progress ))
                break
            fi
        fi
    done
}

if [ "$#" -eq 0 ]; then
    "${SOURCES_PATH}/pwb_browser"
elif [[ "$1" == "help" ]]; then
    if [ "$#" -eq 1 ]; then
        show_usage
    else
        declare func="$2"
        declare path="${SOURCES_PATH}/$func"
        if [ -f "$path" ]; then
            source "$path"
            declare READ_ARGS_SHOW_USAGE=1
            "$func"
            show_func_doc "$path"
        else
            printf $'Unrecognized scriptlet "\e[32;1m%s\e[m"\n' "$func"
        fi
    fi
elif [[ "$1" == "man" ]]; then
    declare path_manfile="${SOURCES_PATH}/${2}.7"
    if ! [ -f "$path_manfile" ]; then
        path_manfile="${SOURCES_PATH}/pwb_${2}.7"
    fi
    if [ -f "$path_manfile" ]; then
        man -l "$path_manfile"
    else
        printf "Can't find man page for '%s'.\n" "$2"
        read -sn1
    fi
elif [[ "$1" == "all" ]]; then
    declare -a SOURCES_INVENTORY
    get_scripts_inventory SOURCES_INVENTORY
    return_sources_script "${SOURCES_INVENTORY[@]}"
else
    return_sources_script "$@"
fi
