#!/usr/bin/env bash

##########################
###   DATA FUNCTIONS   ###
##########################

get_data()
{
   local -n gd_return="$1"

   # Get list of files to 'stat' for additional information
   local -a gd_files
   shopt -s nullglob
   gd_files=( * )
   shopt -u nullglob

   # Get table for cross-referencing file types to color,
   # according to user's LS_COLORS values or by using
   # 'dircolors' to get the default LS_COLORS value:
   declare -A color_table=()
   create_type_color_reference color_table

   local IFS="$DELIM"
   local colstr

   while read -r; do
       read -ra gd_row <<< "$REPLY"
       colstr="${color_table[${gd_row[1]}]}"
       if [ -z "$colstr" ]; then
           colstr="0"
       fi

       # Use execute color if no other color in use:
       if [ -x "${gd_row[0]}" ] && [[ "$colstr" == "0" ]]; then
           gd_row[1]="executable"
           REPLY="${gd_row[*]}"
           colstr="${color_table[executable]}"
       fi

       # Setting to '0' will cancel highlighting, change value
       # the 39 for using the default foreground color:
       if [[ "$colstr" == "0" ]]; then
           colstr="39"
       fi

       gd_return+=( "$REPLY${DELIM}$colstr" )
   done < <( stat -c "$STAT_FORMAT" "${gd_files[@]}" )
}


################################
### PWB CALLBACK FUNCTIONS   ###
################################

print_line()
{
    local -n pl_dsource="$2"
    IFS="$DELIM" read -ra pl_row <<< "${pl_dsource[$1]}"
    local colspec="${pl_row[@]: -1}"

    # Size the text before applying the colors
    printf -v tline "%-*.*s" "$3" "$3" "${pl_row[0]}"
    printf $'\e[%sm%s\e[39;22m' "$colspec" "$tline"
}

print_top()
{
    local -n pl_dsource="$2"
    IFS="$DELIM" read -ra pt_row <<< "${pl_dsource[$1]}"

    local -i char_count="$3"
    local -a pt_lines=(
        "PWB ACTIONS TEMPLATE"
        "${pt_row[0]}"
        "${pt_row[1]}"
        $'Press "\e[32;1mF1\e[39;22m" or "\e[32;1m?\e[39;22m" for help,  "\e[32;1mq\e[39;22m" to exit.'
    )
    local -a print_array_args=(
        -t 1
        -l 1
        -w "$char_count"
        -c "$TOP_MARGIN"
        -j c
    )

    pwb_print_array pt_lines "${print_array_args[@]}"
}

##########################
###   EXEC FUNCTIONS   ###
##########################

# Generic execute callback that delegates actions to functions
# bound to keys by pwb_keybinder
execute_line()
{
    local keyp="$1"
    local el_psource="$4"

    local -i ecode=0
    local el_func
    if pwb_keybinder func KEYFUNCS -v el_func -k "$keyp"; then
        "$el_func" "$@"
        ecode="$?"
        printf $'\e[H\e[2J'
        pwb print_all "$el_psource"
    fi

    return "$ecode"
}

exec_help()
{
    local eh_keyp
    pwb_keybinder help KEYBINDINGS -v eh_keyp

    # Dispose of key that got us to exec_help:
    shift
    # Rerun execute_line in case the help dialog terminated
    # with a documented key, replacing the discarded keypress
    # argument with the key string returned by pwb_keybinder:
    execute_line "$eh_keyp" "$@"
    local -i ecode="$?"
    if [[ "$eh_keyp" == 'q' ]]; then
        ecode=1
    fi

    return "$ecode"
}

exec_info()
{
    local -n ei_dsource="$3"
    IFS="$DELIM" read -ra ei_row <<< "${ei_dsource[$2]}"

    local -i field_count=$(( "${#ei_row[*]}" - 1 ))
    local -a info_fields=( "${ei_row[@]:0:$field_count}" )

    local ei_lines=()
    printf -v ei_lines[${#ei_lines[*]}] \
           $'Information on file \e[32;1m%s\e[39;22m' \
           "${ei_row[0]}"

    ei_lines+=( "" )
    for (( i=1; i<field_count; ++i )); do
        printf -v ei_lines[${#ei_lines[*]}] "$INFO_FORMAT" \
               "${STAT_LABELS[$i]}" "${info_fields[$i]}"
    done

    pwb_conduct_dialog ei_lines -jl
}

#############################
###   UTILITY FUNCTIONS   ###
#############################

exit_trap() { printf $'\e[39;49;22m\e[H\e[2J'; pwb restore; }

create_type_color_reference()
{
    local array_name="$1"
    local -n ctcr_array="$array_name"

    # Use default colors if LS_COLORS not yet set:
    if [ -z "$LS_COLORS" ]; then
        exec $( dircolors )
    fi

    local -a colors
    if [ -n "$LS_COLORS" ]; then
        IFS=':' read -ra colors <<< "$LS_COLORS"
    fi

    for color in "${colors[@]}"; do
        IFS='=' read -ra color_spec <<< "$color"

        local type_name="${color_spec[0]}"
        local type_color="${color_spec[1]}"

        case "$type_name" in
            di   ) ctcr_array[directory]="$type_color" ;;
            rs   ) ctcr_array[regular]="$type_color" ;;
            ln   ) ctcr_array["symbolic link"]="$type_color" ;;
            pi   ) ctcr_array[fifo]="$type_color" ;;
            so   ) ctcr_array[socket]="$type_color" ;;
            bd   ) ctcr_array["block device special file"]="$type_color" ;;
            "cd" ) ctcr_array["char device special file"]="$type_color" ;;
            ex   ) ctcr_array["executable"]="$type_color" ;;
        esac
    done
}

create_stat_tools()
{
    local -n cst_format="$1"
    local -n cst_labels="$2"
    local cst_info_format_name="$3"
    local -n cst_source="$4"

    local -a cur_formats
    cst_labels=()

    local -i curlen curmax=0

    for el in "${cst_source[@]}"; do
        if (( "${#cur_formats[*]}" == "${#cst_labels[*]}" )); then
            cst_labels+=( "$el" )
            curlen="${#el}"
            if (( curlen > curmax )); then
                curmax="$curlen"
            fi
        else
            cur_formats+=( "$el" )
        fi
    done

    local IFS="$DELIM"
    cst_format="${cur_formats[*]}"
    printf -v "$cst_info_format_name" \
           $'%%-%ds: \e[32;1m%%s\e[39;22m' "$curmax"
}


############################
###   EXECUTION BEGINS   ###
############################

# Establish global DELIM character for creating and splitting arrays:
declare DELIM="|"

# Paired specs to align for presentation
declare -a STAT_ARGS=(
    "name"        "%n"  # must be first element
    "file type"   "%F"  # must be second element
    "size"        "%s"
    "owner"       "%U"
    "permissions" "%A"
    "last change" "%y"
)

declare STAT_FORMAT
declare -a STAT_LABELS
declare INFO_FORMAT
create_stat_tools STAT_FORMAT STAT_LABELS INFO_FORMAT STAT_ARGS

enable pwb

# Using source scripts
declare -a SOURCE_ARGS=(
    pwb_exit_on_error
    pwb_print_array
    pwb_conduct_dialog
    pwb_keybinder
)
source <( pwb_sources "${SOURCE_ARGS[@]}" )

declare -a KEYBINDINGS=(
    "?"      exec_help "Show help"
    "key_f1" exec_help "Show help"
    "i"      exec_info "Inspect file"
)
declare KEYMAP
declare -a KEYFUNCS
pwb_keybinder prep KEYBINDINGS -v KEYMAP -f KEYFUNCS

# Prepare data source
declare -a PDATA
get_data PDATA

# Declare Handle
declare -a DECLARE_ARGS=(
    PDATA
    "${#PDATA[*]}"
    print_line
    -t print_top
    -e execute_line
)
declare PHANDLE
pwb declare PHANDLE "${DECLARE_ARGS[@]}"

# Use 'constant' for consistency in set_margins and print_top:
declare -i TOP_MARGIN=5

# Divide scre using margins:
pwb set_margins PHANDLE "$TOP_MARGIN" 0 0

# Use trap/signal to handle possible abrupt exits
trap exit_trap EXIT SIGINT SIGABRT

pwb init
pwb start PHANDLE -a KEYMAP

## BEGIN_DOC
## Enhancement of pwb_template_divided, base for
## pwb_template_xxx
##
## Associated item data should be stored together
## for efficient access.  Accommodations for array
## use are found in the 'get_data', 'print_line',
## and 'print_top' functions.
##
## As usual, refer to this sample's man page for
## a more detailed discussion of strategies and
## methods.
## END_DOC
