#!/usr/bin/env bash

declare SPATH=$( readlink -f "$0" ) # path to script
declare RPATH="${SPATH%/*}"        # path to directory

enable pwb

source <( pwb_sources pwb_scripts_browser )

declare -a slist=(
    template_minimum
    template_divided
    template_actions
    template_table
    template_ls
    template_filter
)

exit_trap() { printf $'\e[2J'; pwb restore; }
trap exit_trap EXIT SIGINT SIGABRT

pwb init

pwb_scripts_browser slist "$RPATH/../templates"
