#!/usr/bin/env bash

##########################
###   DATA FUNCTIONS   ###
##########################

# Expect a data row will have the following fields.
# The first five are from sources, the final field,
# category, is added
# 0: date
# 1: amount
# 2: name
# 3: type
# 4: memo
# 5: category

read_full_data()
{
    # Array for raw category lines
    local -a gcd_categories

    # These two variables will be accessed indirectly,
    # according to the [name] section headers in the file:
    local gcd_categories_name="gcd_categories"
    local gcd_entries_name="$2"

    # Along with gcd_categories_name, these names are
    # used to indirectly access variables from the calling scope:
    local gcd_cat_labels_name="$1"
    local gcd_cat_colors_name="$3"

    # PTX file to parse
    local gcd_source="$4"

    # Read data from file into section-based arrays:
    local aname gcd_cur_target
    while read -r; do
        if [[ "$REPLY" =~ ^\[([^\]]+)\]$ ]]; then
            aname="${BASH_REMATCH[1]}"
            local -n gcd_cur_name="gcd_${aname}_name"
            gcd_cur_target="$gcd_cur_name"

            local -n gcd_array="$gcd_cur_target"
            gcd_array=()
            continue
        fi
        local ltab=$'\t'
        if [ -n "$gcd_cur_target" ]; then
            local -n gcd_array="$gcd_cur_target"
            # Convert tab delimiters to internal value
            gcd_array+=( "${REPLY//$ltab/$DELIM}" )
        fi
    done < "$gcd_source"

    local -a gcd_row
    local IFS="$DELIM"

    # Process entries, adding a category field if missing:
    local trail=$'\c?'  # DEL/0x7F
    local -n gcd_entries="$gcd_entries_name"

    # Get first row, ensure trailing delimiter adds empty element:x
    read -ra gcd_row <<< "${gcd_entries[0]}$trail"
    gcd_row=( "${gcd_row[@]%$trail}" )

    if (( "${#gcd_row[*]}" == 5 )); then
        local -i index=0
        for row in "${gcd_entries[@]}"; do
            gcd_entries["$index"]="${row}${DELIM}0"
            (( ++index ))
        done
    fi

    # Process raw category table, distributing values to
    # synchronized category labels and category colors arrays.

    declare -n gcd_labels="$gcd_cat_labels_name"
    declare -n gcd_colors="$gcd_cat_colors_name"

    # Empty targets before adding contents:
    gcd_labels=( )
    gcd_colors=( )

    # Populate colors array from categories
    for el in "${gcd_categories[@]}"; do
        IFS="$DELIM" read -ra gcd_row <<< "$el"
        gcd_labels+=( "${gcd_row[0]}" )
        gcd_colors+=( "${gcd_row[1]}" )
    done
}

get_filtered_entries()
{
    local -n gfe_filtered_entries="$1"
    local -i gfe_filter="$2"

    local -a gfe_row
    local -i gfe_row_cat

    local IFS="$DELIM"
    gfe_filtered_entries=()
    for entry in "${SI_ENTRIES[@]}"; do
        read -ra gfe_row <<< "$entry"
        gfe_row_cat="${gfe_row[@]: -1}"
        if (( gfe_row_cat == gfe_filter )); then
            gfe_filtered_entries+=( "$entry" )
        fi
    done
}

mark_matches()
{
    local -n mm_entries="$1"
    local mm_regex="$2"

    local -i regex_len="${#mm_regex[*]}"

    local -a mm_row

    local -i index=0
    local IFS="$DELIM"
    for entry in "${mm_entries[@]}"; do
        read -ra mm_row <<< "$entry"
        mm_row=( "${mm_row[@]:0:6}" )
        if [ "$regex_len" -gt 0 ]; then
            if [[ "$entry" =~ $mm_regex ]]; then
                # printf $'entry "\e[32;1m%s\e[39;22m" matched regex "\e[32;1m%s\e[39;22m"\n' \
                #        "$entry" "$mm_regex"
                mm_row+=( 100 )
            fi
        fi

        mm_entries[$index]="${mm_row[*]}"
        (( ++index ))
    done
}

###########################
###   BOUND FUNCTIONS   ###
###########################

exec_help()
{
    local eh_keyp
    pwb_keybinder help KBINDINGS -v eh_keyp

    shift
    exec_line "$eh_keyp" "$@"
    local -i ecode="$?"
    if [[ "$eh_keyp" == 'q' ]] || [ "$ecode" -ne 0 ]; then
        return 1
    fi
}

exec_categorize()
{
    local -a ec_headlines=(
        "Use arrows to change the focus category."
        "Press ENTER to select the focus category."
        "Type the highlighted letter to quick-select."
    )

    local -a ec_opts=( "Uncategorized" "${SI_CATS[@]}" )
    local keyp selopt
    if pwb_selector ec_opts -jl -k keyp -h ec_headlines -tnumbers -v selopt; then
        local -a ec_row
        local -i rlen
        local -n ec_source="$3"
        local IFS="$DELIM"
        read -r -a ec_row <<< "${ec_source[$2]}"
        local -i curcat="${ec_row[@]: -1}"
        if (( "$curcat" != "$selopt" )); then
            local phandle="$4"
            local -i rlen="${#ec_row[*]}"
            ec_row[$(( rlen-1 ))]="$selopt"
            ec_source[$2]="${ec_row[*]}"
            pwb print_row "$phandle" "$2"
            pwb_exit_on_error
        fi
    fi
}

exec_filter()
{
    local -a ec_headlines=(
        "Use arrows to change the focus category."
        "Press ENTER to select the focus category."
        "Type the highlighted letter to quick-select."
    )

    local -a ec_opts=( "None" "Uncategorized" "${SI_CATS[@]}" )
    local keyp selopt
    if pwb_selector ec_opts -jl -k keyp -h ec_headlines -tnumbers -v selopt; then
        if [[ "$keyp" != $'\e' ]]; then
            SA_FILTER=$(( selopt - 1 ))
            return 1
        fi
    fi

    return 0
}

exec_match()
{
    # Print same way at setup and during interaction
    print_entry()
    {
        # leave room for cursor
        local -i flen=$(( width-1 ))
        local -i rlen=$(( width - ${#cur_regex} - 1 ))
        local spaces
        printf -v spaces "%*.*s" "$rlen" "$rlen" " "
        printf -v em_dialog[2] \
               $'%s\e[5m_\e[25m%s' \
               "$cur_regex" "$spaces"
    }

    local -i width=50
    local -a em_exit_keys=( $'\cm' $'\e' )
    local cur_regex="$SI_REGEX"

    local -a em_dialog=(
        "Match Items with Regular Expression"
        ""
    )
    print_entry

    local em_keyp

    local -a edit_args=(
        cur_regex
        em_keyp
        em_exit_keys
    )

    while ! [[ "$em_keyp" =~ ^[$'\e\cm']$ ]]; do
        pwb_print_message em_dialog -jc
        if pwb_edit_line "${edit_args[@]}"; then
            print_entry
        fi

        mark_matches "$SA_ENTRIES_NAME" "$cur_regex"
        pwb print_all SI_HANDLE
    done

    # Update global SI_REGEX only if ENTER pressed,
    # otherwise, revert to selections of previous SI_REGEX
    if [[ "$em_keyp" == $'\cm' ]]; then
        SI_REGEX="$cur_regex"
    fi

    mark_matches "$SA_ENTRIES_NAME" "$SI_REGEX"
    pwb print_all SI_HANDLE

}

exec_save()
{
    local newname="${FILEROOT}.ptx"

    local -a es_confirm
    printf -v es_confirm[${#es_confirm[*]}] \
           $'About to save \e[32;1m%s\e[39;22m to \e[32;1m%s\e[39;22m' \
           "$OG_FILENAME" "$newname"

    es_confirm+=(
        ""
        "Type Y to save, N or ESC to abort"
    )

    local OP_DELIM=$'\t'

    local -a kallowed=( y Y n N $'\e' )
    local kpressed
    pwb_conduct_dialog es_confirm -a kallowed -r kpressed
    if [[ "$kpressed" =~ ^[yY] ]]; then
        # Collect file data before writing
        local -a es_lines

        # Categories first,
        es_lines=(
            "[categories]"
        )
        # Combine separated category information:
        local -i index=0
        for cat in "${SI_CATS[@]}"; do
            es_lines+=( "${cat}${OP_DELIM}${SI_COLORS[$index]}" )
            (( ++index))
        done

        # Then add entries
        es_lines+=( "[entries]" )
        for entry in "${SI_ENTRIES[@]}"; do
            es_lines+=( "${entry//$DELIM/$OP_DELIM}" )
        done

        IFS=$'\n'
        echo "${es_lines[*]}" > "$newname"
    fi
}

exec_return()
{
    return 1
}

#########################
###   PWB CALLBACKS   ###
#########################

print_line()
{
    local -n pl_dsource="$2"
    local -a pl_row
    IFS="$DELIM" read -ra pl_row <<< "${pl_dsource[$1]}"

    local pl_last_field="${pl_row[@]: -1}"
    if ! [[ "$pl_last_field" =~ ^[-[:digit:]]*$ ]]; then
        read -n1 -p "Press key to clear screen and show analysis"
        printf $'\e[2J'
        IFS="|"
        printf $'\n is now \e[36;1m%s\e[39;22m\n' "${pl_row[*]}"
        printf $'and the last element is "\e[33;1m%s\e[39;22m"\n' "${pl_row[@]: -1}"
        printf $'AKA pl_last_field, "\e[31;1m%s\e[39;22m"\n' "$pl_last_field"
        read -n1 -p Continue
        exit
    fi

    local -i cat="${pl_row[@]: -1}"

    local colspec=""
    if (( "$cat" == 100 )); then
        printf -v colspec $'\e[%sm' "48;5;238"
        printf "%s" "$colspec"
    elif (( "$cat" > 0 )); then
        printf -v colspec $'\e[%sm' "${SI_COLORS[$(( cat -1 ))]}"
        printf "%s" "$colspec"
    fi

    local -i limit="$3"

    printf -v tline "%s${SI_FORMAT}%s" "$colspec" "${pl_row[@]:0:3}" $'\e[39;49;22m'
    printf "%-*.*s" "$limit" "$limit" "$tline"
}

noop_print_left() { :; }
print_left()
{
    local -i index="$1"
    local pl_handle="$5"

    local limit_args=(
        -t "${SI_REGIONS[LM_TOP]}"
        -c "${SI_REGIONS[LM_LINES]}"
        -l "${SI_REGIONS[LM_LEFT]}"
        -w "${SI_REGIONS[LM_WIDE]}"
    )

    local -i left=$(( SI_REGIONS[LM_WIDE] - 2 ))

    local -i rows top
    pwb get_data_count "$pl_handle" -v rows
    pwb get_top_row "$pl_handle" -v top

    local -a scrollbar_args=(
        -s "$rows"
        -t "$top"
        -v "${SI_REGIONS[LM_LINES]}"
    )

    local -a pl_scrollbar
    pwb_get_scroll_bar pl_scrollbar "${scrollbar_args[@]}"

    for block in "${pl_scrollbar[@]}"; do
        printf $'\e[%dG%s\e[1D\e[1E' "$left" "$block"
    done
}

print_top()
{
    local limit_args=(
        -t "${SI_REGIONS[TM_TOP]}"
        -c "${SI_REGIONS[TM_LINES]}"
        -l "${SI_REGIONS[SC_LEFT]}"
        -w "${SI_REGIONS[SC_WIDE]}"
    )

    local -n pt_dsource="$2"
    IFS="$DELIM" read -ra pt_row "${pt_dsource[$1]}"

    local cat_name="Uncagegorized"
    local -i cat_index=$(( ${pt_row[@]: -1} - 1 ))

    if (( cat_index >= 0 )); then
        cat_name="${SI_CATS[$cat_index]}"
        cat_name="${cat_name/&/ }"
    fi

    local -a pt_lines
    printf -v pt_lines[${#pt_lines[*]}] \
           $'Scanning file \e[32;1m%s\e[39;22m' \
           "$OG_FILENAME"

    pt_lines+=(
        "${pt_row[4]}"
        "$cat_name"
    )

    printf -v pt_lines["${#pt_lines[*]}"] $'Press \e[32;1mF1\e[39;22m for help'

    pwb_print_array pt_lines "${limit_args[@]}"
}

print_bottom()
{
    local limit_args=(
        -t "${SI_REGIONS[BM_TOP]}"
        -c "${SI_REGIONS[BM_LINES]}"
        -l "${SI_REGIONS[SC_LEFT]}"
        -w "${SI_REGIONS[SC_WIDE]}"
    )

    local -i index="$1"
    local -n pb_dsource="$2"
    local -i total="${#pb_dsource[*]}"
    local -a lines
    printf -v lines[0] $'Record \e[33;1m%d\e[39;22m out of \e[33;1m%d\e[39;22m' \
           $(( index+1 )) "$total"

    pwb_print_array lines "${limit_args[@]}"
}


exec_line()
{
    local keyp="$1"
    local el_handle="$4"

    local -i ecode=0
    local el_func
    if pwb_keybinder func KEYFUNCS -v el_func -k "$keyp"; then
        "$el_func" "$@"
        ecode="$?"
        printf $'\e[H\e[2J'
        pwb print_all "$el_handle"
    fi

    return "$ecode"
}


###################################
###   INSTANCE PREP FUNCTIONS   ###
###################################

get_content_width()
{
    local -n gcw_wide="$1"
    local -n gcw_array="$2"

    local -i cur_wide
    gcw_wide=0
    for line in "${gcw_array[@]}"; do
        cur_wide="${#line}"
        (( gcw_wide = ( cur_wide >gcw_wide ? cur_wide : gcw_wide ) ))
    done
}

set_instance_margins()
{
    local sim_handle="$1"
    local sim_data="$2"

    local -i data_width
    get_content_width data_width "$sim_data"

    local -A sim_dims
    pwb get_dimensions -A sim_dims

    local -i non_content=$(( sim_dims[screen_cols] - data_width ))
    local -i left right
    (( right = non_content / 2 ))
    (( left = right + (non_content % 2) ))

    local -a sim_margins=( 5 "$right" 2 "$left" )

    pwb set_margins "$sim_handle" "${sim_margins[@]}"
}

announce_empty_file()
{
    local -a aef_lines=( "pwb_txscan" )

    printf -v aef_lines[${#aef_lines[*]}] \
           $'File \e[32;1m%s\e[39;22m contains no transactions.' \
           "$OG_FILENAME"
    aef_lines+=(
        ""
        "Press any key to return."
    )

    pwb_conduct_dialog aef_lines -jc
}

announce_no_files()
{
    local -a anf_lines=(
        "pwb_txscan"
        ""
        "There are no recognized transaction files."
        ""
        "Press any key to exit"
    )

    pwb_conduct_dialog anf_lines -jc
}

is_app_exit_key()
{
    local iaek_keyp="$1"
    [[ "$iaek_keyp" == 'q' ]] ||  [[ "$iaek_keyp" == $'\e' ]]
}

# Initiates a display with the current category filter in force.
# The key that terminates the display is returned for scrutiny
# concerning whether to conclude running the application.
run_with_entries()
{
    local rwe_exit_key_name="$1"
    local rwe_entries_name="$2"

    # Prepare alligning format string for print_line() function:
    local SI_FORMAT
    make_format_string SI_FORMAT "$rwe_entries_name"

    # Establish global regular expression storage
    SI_REGEX=""

    # Get filtered entries count for 'pwb declare' parameters:
    local -n rwe_entries="$rwe_entries_name"
    local -i rwe_entries_count="${#rwe_entries[*]}"

    # Prepare indirect print_left function for 'pwb declare' parameters
    local print_left_func=print_left
    p_print_left() { "$print_left_func" "$@"; }

    # Create Handle
    local -a declare_args=(
        "$rwe_entries_name"
        "$rwe_entries_count"
        print_line
        -e exec_line
        -b print_bottom
        -t print_top
        -l p_print_left
    )

    local SI_HANDLE
    pwb declare SI_HANDLE "${declare_args[@]}"
    pwb_exit_on_error

    # Set margins according to data;
    set_instance_margins SI_HANDLE "$rwe_entries_name"
    # then regions according to margins
    local -A SI_REGIONS
    pwb_get_regions SI_REGIONS SI_HANDLE

    # Remove left-margin scrollbar if not enough entries:
    if (( "$rwe_entries_count" <= SI_REGIONS[CO_LINES] )); then
        print_left_func=noop_print_left
    fi

    local ending_keyp
    declare -a start_args=(
        -a KEYMAP
        -k "$rwe_exit_key_name"
    )

    pwb start SI_HANDLE "${start_args[@]}"
    pwb_exit_on_error
}

start_application()
{
    # Prepare full, unfiltered data from file:
    local -a SI_CATS SI_ENTRIES SI_COLORS
    read_full_data SI_CATS SI_ENTRIES SI_COLORS "$FILENAME"
    local -i SI_ENTRIES_COUNT="${#SI_ENTRIES[*]}"

    if [ "$SI_ENTRIES_COUNT" -eq 0 ]; then
        announce_empty_file
    else
        local -i SA_FILTER=-1
        local -a filtered_entries=()
        local SA_ENTRIES_NAME
        local sa_keyp

        while ! is_app_exit_key "$sa_keyp"; do
            if (( SA_FILTER < 0 )); then
                SA_ENTRIES_NAME="SI_ENTRIES"
            else
                filtered_entries=()
                get_filtered_entries filtered_entries SA_FILTER
                SA_ENTRIES_NAME="filtered_entries"
            fi
            printf $'\e[2J'
            run_with_entries sa_keyp "$SA_ENTRIES_NAME"
        done
    fi
}

#########################
###   MISCELLANEOUS   ###
#########################

make_format_string()
{
    local -n mfs_return="$1"
    local -n mfs_array="$2"

    local IFS="$DELIM"
    local -a mfs_row

    local -i fields=0
    local -i cur_len cur_max
    local -a mfs_maxes

    for line in "${mfs_array[@]}"; do
        read -ra mfs_row <<< "$line"
        if (( fields == 0 )); then
            fields="${#mfs_row[*]}"
            for (( i=0; i<fields; ++i )); do
                mfs_maxes+=( 0 )
            done
        fi

        local -i index=0
        for field in "${mfs_row[@]}"; do
            cur_len="${#field}"
            cur_max="${mfs_maxes[$index]}"
            if (( cur_len > cur_max )); then
                mfs_maxes[$index]="$cur_len"
            fi
            (( ++index ))
        done
    done

    declare -a cspecs

    local sign=""
    local -i index=0
    for len in "${mfs_maxes[@]:0:3}"; do
        if (( index++==1 )); then
            sign=""
        else
            sign="-"
        fi
        cspecs+=( "%${sign}${len}s" )
    done

    IFS=$' '
    mfs_return="${cspecs[*]}"
}

pick_file()
{
    local -n pf_return="$1"

    # Make set of whiptail --menu file entries, consisting of
    # the filename as the tag, and an empty string as the "item":
    local -a file_entries
    for file in *; do
        if [[ "$file" =~ ^.*\.(xml|ptx)$ ]]; then
            file_entries+=( "$file" "" )
        fi
    done

    if (( "${#file_entries[*]}" == 0 )); then
        announce_no_files
        exit
    else
        # Basic whiptail arguments:
        local -a dlg_args=(
            --stdout
            --title "Open a file"
            --menu
            "Pick a file to open"
            18 60
            38
            "${file_entries[@]}"
        )

        local pf_file
        if pf_file=$( dialog "${dlg_args[@]}" ); then
            local -n pf_return="$1"
            pf_return="$pf_file"
            return 0
        fi
    fi


    return 1
}

# This function is called to add category entries to a derived
# ptx file.  The fields must be delimited by tabs, and will
# be immediately converted to the internal IFS value.
prepend_default_categories()
{
    local filename="$1"
    local target_name="ptx_cats.txt"

    declare -a DEF_CATS=(
        [categories]
    )

    # Override any other delimiter so as to use tabs here:
    local DELIM=$'\t'

    # possible categories file in order of precedence
    local -a candidates=(
        "$target_name"
        "~/$target_name"
        "${TOOLS_PATH}/$target_name"
        "${TOOLS_PATH}/default_cats.txt"
    )

    # standardize test for two occurances:
    is_id_line() { [[ "$1" =~ ^\[pwb_txscan\]$ ]]; }

    local first_line
    for path in "${candidates[@]}"; do
        if [ -f "$path" ]; then
            if first_line=$( head -n1 "$path" ); then
                if is_id_line "$first_line"; then
                    break
                fi
            fi
        fi
    done

    if [ -n "$path" ]; then
        local name color
        while read -r line || [[ -n "$line" ]]; do
            if [[ "$line" =~ ^(.+[^[:space:]])[[:space:]]+([[:digit:];]+)$ ]]; then
                name="${BASH_REMATCH[1]}"
                color="${BASH_REMATCH[2]}"
                DEF_CATS+=( "${name}${DELIM}$color" )
            fi
        done < "$path"
    else
        DEF_CATS+=(
            \&Groceries"$DELIM"38\;5\;40
            \&Housing"$DELIM"38\;5\;27
            \&Utilities"$DELIM"38\;5\;226
            \&Entertainment"$DELIM"38\;5\;160
        )
    fi

    local IFS=$'\n'
    echo "${DEF_CATS[*]}" > "$filename"
}

confirm_action()
{
    local -a ac_lines=(
        "Confirm $1"
        ""
        "Y or N?"
        )

    local -a allowed=( y Y n N key_escape )
    local ca_keyp
    pwb_conduct_dialog ac_lines -jc SI_HANDLE -a allowed -r ca_keyp
    [[ "$ca_keyp" =~ Y|y ]]
}

exit_trap()
{
    if [ "$?" -ne 0 ] ;then
       echo
       read -n1 -p "View error before leaving"
    fi
    printf $'\e[H\e[2J'
    if [ -n "$FILEFAKE" ]; then
        rm "$FILEFAKE"
    fi
    pwb restore
}

############################
###   EXECUTION BEGINS   ###
############################

enable pwb

declare -a PSOURCES=(
    pwb_exit_on_error
    pwb_get_regions
    pwb_conduct_dialog
    pwb_print_array
    pwb_print_message
    pwb_get_scroll_bar
    pwb_keybinder
    pwb_edit_line
    pwb_selector
)
source <( pwb_sources "${PSOURCES[@]}" )

declare -a KBINDINGS=(
    "key_f1"     exec_help       "Show help"
    "key_escape" exec_return     "Return"
    "c"          exec_categorize "Categorize Entry"
    "f"          exec_filter     "Filter list"
    "m"          exec_match      "Match Items"
    "s"          exec_save       "Save changes"
)

declare SPATH=$( readlink -f "$0" )
declare TOOLS_PATH="${SPATH%/*}/pwb_txscan.d"

# Using DEL/0x7F for delimiter
declare DELIM=$'\c?'

declare KEYMAP
declare -a KEYFUNCS
pwb_keybinder prep KBINDINGS -v KEYMAP -f KEYFUNCS

declare FILENAME="$1"
declare FILEROOT FILEEXT FILEFAKE

if [ -z "$FILENAME" ]; then
    if ! pick_file FILENAME; then
        echo "No file to open, exiting now."
        exit
    fi
fi

declare OG_FILENAME="$FILENAME"

FILEROOT="${FILENAME%.*}"
FILEEXT="${FILENAME##*.}"

if [[ "$FILEEXT" != "ptx" ]]; then
    FILEFAKE=$( mktemp )
    prepend_default_categories "$FILEFAKE"

    if [[ "$FILEEXT" =~ ^[qo]fx$ ]]; then
        "${TOOLS_PATH}/ofx2ptx" "$FILENAME" >> "$FILEFAKE"
    elif [[ "$FILEEXT" =~ xml ]]; then
        xsltproc --encoding UTF8 "${TOOLS_PATH}/schwab2ptx.xsl" "$FILENAME" >> "$FILEFAKE"
        if [ "$?" -ne 0 ]; then
            read -n1 -p "There was some touble with the transformation."
        fi
    fi

    FILENAME="$FILEFAKE"
fi

trap exit_trap EXIT SIGINT SIGABRT
pwb init

start_application

## BEGIN_DOC
## This script does some unusual things:
## 1. Acquires script location to access scripts in
##    pwb_txscan.d.
## 2. If not given a file to open on the command line,
##    it presents a dialog of filenames from which to
##    pick a file to open.
## 3. Since work can be done, there is an option to
##    save the file.  It's not very clever: you can
##    only save the file with the root and an .ptx
##    extension.
## 4. Supports QFX/OFX (ie from WellsFargo) and a
##    custom solution for the XML format provided
##    by Schwab.  Other sources will likely require
##    other custom solutions.
## 5. Option 's' will save the changes to a file
##    with a ptx extension.
## END_DOC
