#!/usr/bin/env bash

##########################
###   DATA FUNCTIONS   ###
##########################

# Expect a data row will have the following fields.
# The first five are from sources, the final field,
# category, is added
# 0: date
# 1: amount
# 2: name
# 3: type
# 4: memo
# 5: category

get_context_data()
{
    # Array for raw category lines
    local -a gcd_categories

    # These two variables will be accessed indirectly,
    # according to the [name] section headers in the file:
    local gcd_categories_name="gcd_categories"
    local gcd_entries_name="$2"

    # Along with gcd_categories_name, these names are
    # used to indirectly access variables from the calling scope:
    local gcd_cat_labels_name="$1"
    local gcd_cat_colors_name="$3"

    # PTX file to parse
    local gcd_source="$4"

    # Read data from file into section-based arrays:
    local aname gcd_cur_target
    while read -r; do
        if [[ "$REPLY" =~ ^\[([^\]]+)\]$ ]]; then
            aname="${BASH_REMATCH[1]}"
            local -n gcd_cur_name="gcd_${aname}_name"
            gcd_cur_target="$gcd_cur_name"

            local -n gcd_array="$gcd_cur_target"
            gcd_array=()
            continue
        fi
        if [ -n "$gcd_cur_target" ]; then
            local -n gcd_array="$gcd_cur_target"
            gcd_array+=( "$REPLY" )
        fi
    done < "$gcd_source"

    local -a gcd_row
    local IFS="$DELIM"

    # Process entries, adding a category field if missing:
    local trail=$'\c?'  # DEL/0x7F
    local -n gcd_entries="$gcd_entries_name"

    # Get first row, ensure trailing delimiter adds empty element:x
    read -r -a gcd_row <<< "${gcd_entries[0]}$trail"
    gcd_row=( "${gcd_row[@]%$trail}" )

    if (( "${#gcd_row[*]}" == 5 )); then
        local -i index=0
        for row in "${gcd_entries[@]}"; do
            gcd_entries["$index"]="${row}${DELIM}0"
            (( ++index ))
        done
    fi

    # Process raw category table, distributing values to
    # synchronized category labels and category colors arrays.

    declare -n gcd_labels="$gcd_cat_labels_name"
    declare -n gcd_colors="$gcd_cat_colors_name"

    # Empty targets before adding contents:
    gcd_labels=( )
    gcd_colors=( )

    # Populate colors array from categories
    for el in "${gcd_categories[@]}"; do
        IFS="$DELIM" read -ra gcd_row <<< "$el"
        gcd_labels+=( "${gcd_row[0]}" )
        gcd_colors+=( "${gcd_row[1]}" )
    done
}

###########################
###   BOUND FUNCTIONS   ###
###########################

exec_help()
{
    local eh_keyp
    pwb_keybinder help KBINDINGS -v eh_keyp

    shift
    exec_line "$eh_keyp" "$@"
    local -i ecode="$?"
    if [[ "$eh_keyp" == 'q' ]] || [ "$ecode" -ne 0 ]; then
        return 1
    fi
}

exec_categorize()
{
    local -a ec_opts=( "Uncategorized" "${SI_CATS[@]}" )
    local keyp selopt
    if pwb_selector ec_opts -jl -k keyp -tnumbers -v selopt; then
        local -a ec_row
        local -i rlen
        local -n ec_source="$3"
        local IFS="$DELIM"
        read -r -a ec_row <<< "${ec_source[$2]}"
        local -i curcat="${ec_row[@]: -1}"
        if (( "$curcat" != "$selopt" )); then
            local phandle="$4"
            local -i rlen="${#ec_row[*]}"
            ec_row[$(( rlen-1 ))]="$selopt"
            ec_source[$2]="${ec_row[*]}"
            pwb print_row "$phandle" "$2"
            pwb_exit_on_error
        fi
    fi
}

exec_save()
{
    # Collect file data before writing
    local -a es_lines

    # Categories first,
    es_lines=(
        "[categories]"
    )
    # Combine separated category information:
    local -i index=0
    for cat in "${SI_CATS[@]}"; do
        es_lines+=( "${cat}${DELIM}${SI_COLORS[$index]}" )
        (( ++index))
    done

    # Then add entries
    es_lines+=(
        "[entries]"
        "${SI_ENTRIES[@]}"
    )

    # Save the staged data:
    local newname="${FILEROOT}.ptx"
    read -n1 -p "About to save ${#es_lines[*]} lines to '$newname'"

    IFS=$'\n'
    echo "${es_lines[*]}" > "$newname"
}

exec_return()
{
    return 1
}

#########################
###   PWB CALLBACKS   ###
#########################

print_line()
{
    local -n pl_dsource="$2"
    local -a pl_row
    IFS="$DELIM" read -r -a pl_row <<< "${pl_dsource[$1]}"
    local -i cat="${pl_row[@]: -1}"

    local colspec=""
    if (( "$cat" > 0 )); then
        printf -v colspec $'\e[%sm' "${SI_COLORS[$(( cat -1 ))]}"
        printf "%s" "$colspec"
    fi

    local -i limit="$3"

    printf -v tline "%s${SI_FORMAT}%s" "$colspec" "${pl_row[@]:0:3}" $'\e[39;22m'
    printf "%-*.*s" "$limit" "$limit" "$tline"
}

noop_print_left() { :; }
print_left()
{
    local -i index="$1"
    local pl_handle="$5"

    local limit_args=(
        -t "${SI_REGIONS[LM_TOP]}"
        -c "${SI_REGIONS[LM_LINES]}"
        -l "${SI_REGIONS[LM_LEFT]}"
        -w "${SI_REGIONS[LM_WIDE]}"
    )

    local -i left=$(( SI_REGIONS[LM_WIDE] - 2 ))

    local -i rows top
    pwb get_data_count "$pl_handle" -v rows
    pwb get_top_row "$pl_handle" -v top

    local -a scrollbar_args=(
        -s "$rows"
        -t "$top"
        -v "${SI_REGIONS[LM_LINES]}"
    )

    local -a pl_scrollbar
    pwb_get_scroll_bar pl_scrollbar "${scrollbar_args[@]}"

    for block in "${pl_scrollbar[@]}"; do
        printf $'\e[%dG%s\e[1D\e[1E' "$left" "$block"
    done
}

print_top()
{
    local limit_args=(
        -t "${SI_REGIONS[TM_TOP]}"
        -c "${SI_REGIONS[TM_LINES]}"
        -l "${SI_REGIONS[SC_LEFT]}"
        -w "${SI_REGIONS[SC_WIDE]}"
    )

    local -n pt_dsource="$2"
    IFS="$DELIM" read -ra pt_row <<< "${pt_dsource[$1]}"

    local cat_name="Uncagegorized"
    local -i cat_index=$(( ${pt_row[@]: -1} - 1 ))
    if (( cat_index >= 0 )); then
        cat_name="${SI_CATS[$cat_index]}"
        cat_name="${cat_name/&/ }"
    fi

    local -a pt_lines=(
        "PWB TRANSACTION SCANNER"
        "${pt_row[4]}"
        "$cat_name"
    )

    printf -v pt_lines["${#pt_lines[*]}"] "Press F1 for help"

    pwb_print_array pt_lines "${limit_args[@]}"
}

print_bottom()
{
    local limit_args=(
        -t "${SI_REGIONS[BM_TOP]}"
        -c "${SI_REGIONS[BM_LINES]}"
        -l "${SI_REGIONS[SC_LEFT]}"
        -w "${SI_REGIONS[SC_WIDE]}"
    )

    local -i index="$1"
    local -n pb_dsource="$2"
    local -i total="${#pb_dsource[*]}"
    local -a lines
    printf -v lines[0] $'Record \e[33;1m%d\e[39;22m out of \e[33;1m%d\e[39;22m' \
           $(( index+1 )) "$total"

    pwb_print_array lines "${limit_args[@]}"
}


exec_line()
{
    local keyp="$1"
    local el_handle="$4"

    local -i ecode=0
    local el_func
    if pwb_keybinder func KEYFUNCS -v el_func -k "$keyp"; then
        "$el_func" "$@"
        ecode="$?"
        printf $'\e[H\e[2J'
        pwb print_all "$el_handle"
    fi

    return "$ecode"
}


###################################
###   INSTANCE PREP FUNCTIONS   ###
###################################

get_content_width()
{
    local -n gcw_wide="$1"
    local -n gcw_array="$2"

    local -i cur_wide
    gcw_wide=0
    for line in "${gcw_array[@]}"; do
        cur_wide="${#line}"
        (( gcw_wide = ( cur_wide >gcw_wide ? cur_wide : gcw_wide ) ))
    done
}

set_instance_margins()
{
    local sim_handle="$1"
    local sim_data="$2"

    local -i data_width
    get_content_width data_width "$sim_data"

    local -A sim_dims
    pwb get_dimensions -A sim_dims

    local -i non_content=$(( sim_dims[screen_cols] - data_width ))
    local -i left right
    (( right = non_content / 2 ))
    (( left = right + (non_content % 2) ))

    local -a sim_margins=( 5 "$right" 2 "$left" )

    pwb set_margins "$sim_handle" "${sim_margins[@]}"
}

start_instance()
{
    # Prepare Data
    local -a SI_CATS SI_ENTRIES SI_COLORS
    get_context_data SI_CATS SI_ENTRIES SI_COLORS "$FILENAME"
    local -i SI_ENTRIES_COUNT="${#SI_ENTRIES[*]}"

    if [ "$SI_ENTRIES_COUNT" -eq 0 ]; then
        declare -a si_lines
        printf -v si_lines["${#si_lines[*]}"] \
               $'Directory \e[32;1m%s\e[39;22m is empty' "$PWD"
        si_lines+=(
            ""
            "Press any key to return."
        )
        pwb_conduct_dialog si_lines
    else
        local print_left_func=print_left
        p_print_left() { "$print_left_func" "$@"; }

        local SI_FORMAT
        make_format_string SI_FORMAT SI_ENTRIES

        # Create Handle
        local -a declare_args=(
            SI_ENTRIES
            "$SI_ENTRIES_COUNT"
            print_line
            -e exec_line
            -b print_bottom
            -t print_top
            -l p_print_left
        )

        local SI_HANDLE
        pwb declare SI_HANDLE "${declare_args[@]}"
        pwb_exit_on_error

        # Prepare Handle
        set_instance_margins SI_HANDLE SI_ENTRIES

        # With margins established, get instance-global regions
        local -A SI_REGIONS
        pwb_get_regions SI_REGIONS SI_HANDLE

        # Use do-nothing function for scrollbar not needed:
        if (( SI_ENTRIES_COUNT <= SI_REGIONS[CO_LINES] )); then
            print_left_func=noop_print_left
        fi

        local ending_keyp
        declare -a start_args=(
            -a KEYMAP
            -k ending_keyp
        )

        pwb start SI_HANDLE "${start_args[@]}"
        pwb_exit_on_error

        if [[ "$ending_keyp" == 'q' ]]; then
            exit 0
        fi
    fi
}

#########################
###   MISCELLANEOUS   ###
#########################

make_format_string()
{
    local -n mfs_return="$1"
    local -n mfs_array="$2"

    local IFS="$DELIM"
    local -a mfs_row

    local -i fields=0
    local -i cur_len cur_max
    local -a mfs_maxes

    for line in "${mfs_array[@]}"; do
        IFS="$DELIM" read -r -a mfs_row <<< "$line"
        if (( fields == 0 )); then
            fields="${#mfs_row[*]}"
            for (( i=0; i<fields; ++i )); do
                mfs_maxes+=( 0 )
            done
        fi

        local -i index=0
        for field in "${mfs_row[@]}"; do
            cur_len="${#field}"
            cur_max="${mfs_maxes[$index]}"
            if (( cur_len > cur_max )); then
                mfs_maxes[$index]="$cur_len"
            fi
            (( ++index ))
        done
    done

    declare -a cspecs

    local sign=""
    local -i index=0
    for len in "${mfs_maxes[@]:0:3}"; do
        if (( index++==1 )); then
            sign=""
        else
            sign="-"
        fi
        cspecs+=( "%${sign}${len}s" )
    done

    IFS=$' '
    mfs_return="${cspecs[*]}"
}

pick_file()
{
    local -n pf_return="$1"

    # Basic whiptail arguments:
    local -a dlg_args=(
        --stdout
        --title "Open a file"
        --menu
        "Pick a file to open"
        18 40
        38
    )

    # Add tag/item menu entries with filename and empty string pairs:
    for file in *; do
        dlg_args+=( "$file" "" )
    done

    local pf_file
    if pf_file=$( dialog "${dlg_args[@]}" ); then
        local -n pf_return="$1"
        pf_return="$pf_file"
        return 0
    fi

    return 1
}

prepend_default_categories()
{
    local filename="$1"
    local target_name="ptx_cats.txt"

    declare -a DEF_CATS=(
        [categories]
    )

    # possible categories file in order of precedence
    local -a candidates=(
        "$target_name"
        "~/$target_name"
        "${TOOLS_PATH}/$target_name"
        "${TOOLS_PATH}/default_cats.txt"
    )

    # standardize test for two occurances:
    is_id_line() { [[ "$1" =~ ^\[pwb_txscan\]$ ]]; }

    local first_line
    for path in "${candidates[@]}"; do
        if [ -f "$path" ]; then
            if first_line=$( head -n1 "$path" ); then
                if is_id_line "$first_line"; then
                    break
                fi
            fi
        fi
    done

    if [ -n "$path" ]; then
        local name color
        while read -r line || [[ -n "$line" ]]; do
            if [[ "$line" =~ ^(.+[^[:space:]])[[:space:]]+([[:digit:];]+)$ ]]; then
                name="${BASH_REMATCH[1]}"
                color="${BASH_REMATCH[2]}"
                DEF_CATS+=( "${name}${DELIM}$color" )
            fi
        done < "$path"
    else
        DEF_CATS+=(
            \&Groceries"$DELIM"38\;5\;40
            \&Housing"$DELIM"38\;5\;27
            \&Utilities"$DELIM"38\;5\;226
            \&Entertainment"$DELIM"38\;5\;160
        )
    fi

    local IFS=$'\n'
    echo "${DEF_CATS[*]}" > "$filename"
}

exit_trap()
{
    printf $'\e[H\e[2J'
    if [ -n "$FILEFAKE" ]; then
        rm "$FILEFAKE"
    fi
    pwb restore
}

############################
###   EXECUTION BEGINS   ###
############################

enable pwb

declare -a PSOURCES=(
    pwb_exit_on_error
    pwb_get_regions
    pwb_conduct_dialog
    pwb_print_array
    pwb_get_scroll_bar
    pwb_keybinder
    pwb_selector
)
source <( pwb_sources "${PSOURCES[@]}" )

declare -a KBINDINGS=(
    "key_f1"     exec_help       "Show help"
    "key_escape" exec_return     "Return"
    "c"          exec_categorize "Categorize Entry"
    "s"          exec_save       "Save changes"
)

declare SPATH=$( readlink -f "$0" )
declare TOOLS_PATH="${SPATH%/*}/pwb_txscan.d"

declare DELIM=$'\c?'

declare KEYMAP
declare -a KEYFUNCS
pwb_keybinder prep KBINDINGS -v KEYMAP -f KEYFUNCS

declare FILENAME="$1"
declare FILEROOT FILEEXT FILEFAKE

if [ -z "$FILENAME" ]; then
    if ! pick_file FILENAME; then
        echo "No file to open, exiting now."
        exit 1
    fi
fi

FILEROOT="${FILENAME%.*}"
FILEEXT="${FILENAME##*.}"

if [[ "$FILEEXT" != "ptx" ]]; then
    FILEFAKE=$( mktemp )
    prepend_default_categories "$FILEFAKE"

    if [[ "$FILEEXT" =~ ^[qo]fx$ ]]; then
        "${TOOLS_PATH}/ofx2ptx" "$FILENAME" >> "$FILEFAKE"
    elif [[ "$FILEEXT" =~ xml ]]; then
        xsltproc --encoding UTF8 "${TOOLS_PATH}/schwab2ptx.xsl" "$FILENAME" >> "$FILEFAKE"
        if [ "$?" -ne 0 ]; then
            read -n1 -p "There was some touble with the transformation."
        fi
    fi

    FILENAME="$FILEFAKE"
fi

trap exit_trap EXIT SIGINT SIGABRT
pwb init

start_instance

## BEGIN_DOC
## This script does some unusual things:
## 1. Acquires script location to access scripts in
##    pwb_txscan.d.
## 2. If not given a file to open on the command line,
##    it presents a dialog of filenames from which to
##    pick a file to open.
## 3. Since work can be done, there is an option to
##    save the file.  It's not very clever: you can
##    only save the file with the root and an .ptx
##    extension.
## 4. Supports QFX/OFX (ie from WellsFargo) and a
##    custom solution for the XML format provided
##    by Schwab.  Other sources will likely require
##    other custom solutions.
## 5. Option 's' will save the changes to a file
##    with a ptx extension.
## END_DOC
