#!/usr/bin/env bash

##
## Use this template to perform an action on a user-selected
## set of files.  Function 'exec_perform_action' below can be
## modified to execute your intentions for the files.
##
## The comment with "MODIFICATION SITE" shows where one might
## begin using the selection.
##
## The comments "DEMO CODE" just perform a meaningless action
## so the template actually does something.  Replace or delete
## as you see fit.
##

##########################
###   DATA FUNCTIONS   ###
##########################

get_context_data()
{
    local -n gcd_return="$1"

    local -a gcd_files
    while read -r; do
        gcd_files+=( "${REPLY}${DELIM}0" )
    done < <( ls -1 )

    for fname in "${gcd_files[@]}"; do
        if [ -d "$fname" ]; then
            gcd_return+=( "*$fname" )
        else
            gcd_return+=( "$fname" )
        fi
    done
}

###########################
###   BOUND FUNCTIONS   ###
###########################

exec_help()
{
    local eh_keyp
    pwb_keybinder help KBINDINGS -v eh_keyp

    shift
    exec_line "$eh_keyp" "$@"
    local -i ecode="$?"
    if [[ "$eh_keyp" == 'q' ]] || [ "$ecode" -ne 0 ]; then
        return 1
    fi
}

exec_select()
{
    local -n es_data="$3"
    local -a es_row
    IFS="$DELIM" read -r -a es_row <<< "${es_data[$2]}"

    # Update data row and table
    local IFS="$DELIM"
    es_row[1]=1
    es_data[$2]="${es_row[*]}"

    local es_phandle="$4"

    # Print updated line
    pwb print_row "$es_phandle" "$2"
    pwb_exit_on_error

    # Move to next row
    pwb trigger "$es_phandle" 1
    pwb_exit_on_error
}

exec_unselect()
{
    local -n eu_data="$3"
    local -a eu_row
    IFS="$DELIM" read -r -a eu_row <<< "${eu_data[$2]}"

    # Update data row and table
    local IFS="$DELIM"
    eu_row[1]=0
    eu_data[$2]="${eu_row[*]}"

    local eu_phandle="$4"

    # Print updated line
    pwb print_row "$eu_phandle" "$2"

    # Move to next row
    pwb trigger "$eu_phandle" 1
}

exec_toggle()
{
    local -n et_data="$3"
    local -a et_row
    IFS="$DELIM" read -r -a et_row <<< "${et_data[$2]}"

    # New value from old
    local -i newval=0
    if [ "${et_row[1]}" -eq 0 ]; then
        newval=1
    fi

    # Update data row and table
    local IFS="$DELIM"
    et_row[1]="$newval"
    et_data[$2]="${et_row[*]}"

    local et_phandle="$4"

    # Print updated line
    pwb print_row "$et_phandle" "$2"

    # Move to next row
    pwb trigger "$et_phandle" 1
}

exec_perform_action()
{
    local keyp="$1"
    local -i index="$2"
    local -n epa_data="$3"
    local epa_phandle="$4"

    local raw_row
    local -a epa_row
    local -a selected_files

    for raw_row in "${epa_data[@]}"; do
        IFS="$DELIM" read -r -a epa_row <<< "$raw_row"
        if [ "${epa_row[1]}" -ne 0 ]; then
            local filename="${epa_row[0]}"
            # MODIFICATION SITE: use the $filename as you wish

            # This DEMO CODE just collects the selected file names.
            # Replace the following with the action you want
            # performed for the selected file:
            selected_files+=( "$filename" )
        fi
    done

    # DEMO CODE: display the selected list of files
    # Delete, modify, or replace until the end of the function

    pwb get_dimensions
    local -i maxlen=$(( ${PWB_ASSOC[screen_cols]} - 2 ))

    local -a displines=( "Selected Files" "" )

    local -a curline
    local -i linelen=0
    local -i count=0
    local IFS=""

    for f in "${selected_files[@]}"; do
        # After first element, always add comma to previous element
        if (( count++ > 0 )); then
            curline+=( ", " )
            (( linelen += 2 ))
        fi

        curlen="${#f}"
        if (( linelen + curlen < maxlen )); then
            curline+=( "$f" )
            (( linelen += curlen + 1 ))
        else
            displines+=( "${curline[*]}" )
            curline=( "$f" )
            linelen="$curlen"
        fi
    done
    if [ "${#curline[*]}" -ne 0 ]; then
        displines+=( "${curline[*]}" )
    fi

    pwb_conduct_dialog displines "$epa_phandle"
}

#########################
###   PWB CALLBACKS   ###
#########################

print_line()
{
    local -n pl_data="$2"
    local -a pl_row
    IFS="$DELIM" read -r -a pl_row <<< "${pl_data[$1]}"

    # allow space for "[x] " (4 characters)
    local -i name_allowance=$(( $3 - 4 ))
    local selchar=" "
    if [ "${pl_row[1]}" -ne 0 ]; then
        selchar="$SELCHAR"
    fi

    printf $'[%c] %-*.*s' "$selchar" \
           "$name_allowance" "$name_allowance" "${pl_row[0]}"
}

noop_print_left() { :; }
print_left()
{
    local -i index="$1"
    local pl_handle="$5"

    local limit_args=(
        -t "${SI_REGIONS[LM_TOP]}"
        -c "${SI_REGIONS[LM_LINES]}"
        -l "${SI_REGIONS[LM_LEFT]}"
        -w "${SI_REGIONS[LM_WIDE]}"
    )

    local -i left=$(( SI_REGIONS[LM_WIDE] - 2 ))

    local -i rows top
    pwb get_data_count "$pl_handle" -v rows
    pwb get_top_row "$pl_handle" -v top

    local -a scrollbar_args=(
        -s "$rows"
        -t "$top"
        -v "${SI_REGIONS[LM_LINES]}"
    )

    local -a pl_scrollbar
    pwb_get_scroll_bar pl_scrollbar "${scrollbar_args[@]}"

    for block in "${pl_scrollbar[@]}"; do
        printf $'\e[%dG%s\e[1D\e[1E' "$left" "$block"
    done
}

print_top()
{
    local limit_args=(
        -t "${SI_REGIONS[TM_TOP]}"
        -c "${SI_REGIONS[TM_LINES]}"
        -l "${SI_REGIONS[SC_LEFT]}"
        -w "${SI_REGIONS[SC_WIDE]}"
    )

    local -a pt_lines=( "PWB TEMPLATE SELECT FILES" )

    printf -v pt_lines["${#pt_lines[*]}"] "Press F1 for help"

    pwb_print_array pt_lines "${limit_args[@]}"
}

print_bottom()
{
    local limit_args=(
        -t "${SI_REGIONS[BM_TOP]}"
        -c "${SI_REGIONS[BM_LINES]}"
        -l "${SI_REGIONS[SC_LEFT]}"
        -w "${SI_REGIONS[SC_WIDE]}"
    )

    local -i index="$1"
    local -i total="${#SI_DATA[*]}"
    local -a lines
    printf -v lines[0] $'Record \e[33;1m%d\e[39;22m out of \e[33;1m%d\e[39;22m' \
           $(( index+1 )) "$total"

    pwb_print_array lines "${limit_args[@]}"
}


exec_line()
{
    local keyp="$1"
    local el_handle="$4"

    local -i ecode=0
    local el_func
    if pwb_keybinder func KEYFUNCS -v el_func -k "$keyp"; then
        "$el_func" "$@"
        ecode="$?"
        printf $'\e[H\e[2J'
        pwb print_all "$el_handle"
    fi

    return "$ecode"
}


###################################
###   INSTANCE PREP FUNCTIONS   ###
###################################

get_content_width()
{
    local -n gcw_wide="$1"
    local -n gcw_array="$2"

    local -i cur_wide
    gcw_wide=0
    for line in "${gcw_array[@]}"; do
        cur_wide="${#line}"
        (( gcw_wide = ( cur_wide >gcw_wide ? cur_wide : gcw_wide ) ))
    done

    # Add space for selection indicator character:
    (( pcw_wide += 2 ))
}

set_instance_margins()
{
    local sim_handle="$1"
    local sim_data="$2"

    local -i data_width
    get_content_width data_width "$sim_data"

    local -A sim_dims
    pwb get_dimensions -A sim_dims

    local -i non_content=$(( sim_dims[screen_cols] - data_width ))
    local -i left right
    (( right = non_content / 2 ))
    (( left = right + (non_content % 2) ))

    local -a sim_margins=( 5 "$right" 2 "$left" )

    pwb set_margins "$sim_handle" "${sim_margins[@]}"
}

start_instance()
{
    # Prepare Data
    local -a SI_DATA
    get_context_data SI_DATA
    local -i SI_DATA_COUNT="${#SI_DATA[*]}"

    if [ "$SI_DATA_COUNT" -eq 0 ]; then
        declare -a si_lines
        printf -v si_lines["${#si_lines[*]}"] \
               $'Directory \e[32;1m%s\e[39;22m is empty' "$PWD"
        si_lines+=(
            ""
            "Press any key to return."
        )
        pwb_conduct_dialog si_lines
    else
        local print_left_func=print_left
        p_print_left() { "$print_left_func" "$@"; }

        # Create Handle
        local -a declare_args=(
            SI_DATA
            "$SI_DATA_COUNT"
            print_line
            -e exec_line
            -b print_bottom
            -t print_top
            -l p_print_left
        )

        local SI_HANDLE
        pwb declare SI_HANDLE "${declare_args[@]}"
        pwb_exit_on_error

        # Prepare Handle
        set_instance_margins SI_HANDLE SI_DATA

        # With margins established, get instance-global regions
        local -A SI_REGIONS
        pwb_get_regions SI_REGIONS SI_HANDLE

        # Use do-nothing function for scrollbar not needed:
        if (( SI_DATA_COUNT <= SI_REGIONS[CO_LINES] )); then
            print_left_func=noop_print_left
        fi

        local ending_keyp
        declare -a start_args=(
            -a KEYMAP
            -k ending_keyp
        )

        pwb start SI_HANDLE "${start_args[@]}"
        pwb_exit_on_error

        if [[ "$ending_keyp" == 'q' ]]; then
            exit 0
        fi
    fi
}

#########################
###   MISCELLANEOUS   ###
#########################

exit_trap() { printf $'\e[H\e[2J'; pwb restore; }

############################
###   EXECUTION BEGINS   ###
############################

enable pwb

declare DELIM="|"
declare SELCHAR=$'x'

declare -a PSOURCES=(
    pwb_exit_on_error
    pwb_get_regions
    pwb_conduct_dialog
    pwb_print_array
    pwb_get_scroll_bar
    pwb_keybinder
)
source <( pwb_sources "${PSOURCES[@]}" )

declare -a KBINDINGS=(
    "key_f1"  exec_help     "Show help"
    "+"       exec_select   "Select line"
    "="       exec_select   "Select line"
    "-"       exec_unselect "Unselect line"
    't'       exec_toggle   "Toggle line select"
    $'\cm'    exec_perform_action "Perform action on selections"
)

declare KEYMAP
declare -a KEYFUNCS
pwb_keybinder prep KBINDINGS -v KEYMAP -f KEYFUNCS

trap exit_trap EXIT SIGINT SIGABRT
pwb init

declare OG_DIR="$PWD"
cd /

declare -a DIR_STEPS=( "$PWD" )

start_instance

cd "$OG_DIR"

## BEGIN_DOC
## This script demonstrates how to implement a
## checkbox interaction using pwb.
##
## It includes the stub of an action function,
## 'exec_perform_action' that can be copied
## and/or modified to perform some domain-
## specific objectives.
## END_DOC
