#!/usr/bin/env bash

#########################
###   PWB CALLBACKS   ###
#########################

print_line()
{
    local -n pl_dsource="$2"
    printf "%-*.*s" "$3" "$3" "${pl_dsource[$1]}"
}

#########################
###   MISCELLANEOUS   ###
#########################

exit_trap() { printf $'\e[H\e[2J'; pwb restore; }

############################
###   EXECUTION BEGINS   ###
############################

enable pwb

declare -a PSOURCES=(
    pwb_exit_on_error
)
source <( pwb_sources "${PSOURCES[@]}" )

shopt -s nullglob
declare -a PDATA=( * )
shopt -u nullglob

declare -a PARGS=(
    PDATA
    "${#PDATA[*]}"
    print_line
)
declare PHANDLE
pwb declare PHANDLE "${PARGS[@]}"

trap exit_trap EXIT SIGINT SIGABRT

pwb init
pwb start PHANDLE

## BEGIN_DOC
## The essential bare minimum script that
## allows a user to browse a dataset, in this
## case, the files in the current directory.
## END_DOC
