#!/usr/bin/env bash

# Data function(s)
get_data()
{
   local -n gd_return="$1"

   shopt -s nullglob
   gd_return=( * )
   shopt -u nullglob
}

# PWB callback function(s)

print_line()
{
    # Skip naming 'index' and 'char_count' for basic print
    local -n pl_dsource="$2"
    printf "%-*.*s" "$3" "$3" "${pl_dsource[$1]}"
}

print_top()
{
    # Collect info
    local -i total index="$1"
    local handle_name="$5"

    pwb get_data_count "$handle_name" -v total
    pwb_exit_on_error
    printf -v progress_line \
           $'Item \e[32;1m%d\e[39;22m of \e[32;1m%d\e[39;22m.' \
           $(( index+1 )) "$total"

    # Create array for printing
    local -a pt_lines=(
        "PWB DIVIDED TEMPLATE"
        "$progress_line"
        ""
        $'Press "\e[32;1mq\e[39;22m" to exit.'
    )

    # Measure and prepare arguments for pwb_print_array
    pwb get_dimensions
    local -a print_array_args=(
        -t 1
        -l 1
        -w "${PWB_ASSOC[screen_cols]}"
        -c 4
        -j c
    )

    pwb_print_array pt_lines "${print_array_args[@]}"
}

# PWB setup

# Set top margin for info, side margins for centering
set_margins()
{
   local sm_handle="$1"
   local -n sm_data="$2"

   # Measure width of data
   local -i curlen maxlen=0
   for item in "${sm_data[@]}"; do
       curlen="${#item}"
       if (( curlen > maxlen )); then
           maxlen="$curlen"
       fi
   done

   pwb get_dimensions
   local -i left right columns="${PWB_ASSOC[screen_cols]}"

   # Only center if at least 2 spare spaces
   if (( columns > maxlen+1 )); then
       (( right = (columns - maxlen) / 2 ))
       (( left = columns - maxlen - right ))
   else
       (( left = 0; right = 0 ))
   fi

   pwb set_margins "$sm_handle" 5 "$right" 1 "$left"
}

# Trap signal to handle abrupt exits
exit_trap() { printf $'\e[39;49;22m\e[H\e[2J'; pwb restore; }

# Separate function declarations from global execution:

enable pwb

# Using source scripts
declare -a SOURCE_ARGS=(
    pwb_exit_on_error
    pwb_print_array
)
source <( pwb_sources "${SOURCE_ARGS[@]}" )

# Prepare data source
declare -a PDATA
get_data PDATA

# Declare Handle
declare -a DECLARE_ARGS=(
    PDATA
    "${#PDATA[*]}"
    print_line
    -t print_top
)
declare PHANDLE
pwb declare PHANDLE "${DECLARE_ARGS[@]}"

set_margins PHANDLE PDATA

# Use trap/signal to handle possible abrupt exits
trap exit_trap EXIT SIGINT SIGABRT

pwb init
pwb start PHANDLE

## BEGIN_DOC
## This script introduces good behavior features.
## Second in a progression of template scripts.
##
## 1. The screen is split to include a top margin
##    area to provide usage information.
## 2. Using trap/signal to restore the terminal
##    in case of early exit due to an error.
## 3. Introduce pwb_sources, a library of
##    utilities for doing common useful things.
## END_DOC
