.so fork.tmac
.SH SYNOPSIS
.B enable pwb
.PP
.pt_help
.pt_version
.SS SCREEN SETUP
.pt_init
.pt_restore
.SS RESOURCE CREATION
.pt_declare
.pt_declare_keymap
.SS RUNNING THE PAGER
.pt_start
.pt_set_margins
.pt_print_row
.pt_print_all
.pt_trigger
.SS CALLBACK FUNCTIONS
.pt_print_callback
.pt_exec_callback
.SS MISCELLANEOUS
.pt_get_dimensions

.pt_get_data_source
.pt_get_data_count
.pt_set_data_count

.pt_get_top_row
.pt_get_focus_row
.pt_set_focus_row

.pt_measure_string
.pt_limit_print

.pt_get_keystroke
